package com.ds.report.entity.mapper;

import com.ds.report.entity.DsGFLotteryEntity;
import com.ds.report.entity.DsGFLotteryEntityExample;
import com.ds.report.entity.DsGFLotteryEntityWithBLOBs;
import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DsGFLotteryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int countByExample(DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int deleteByExample(DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int insert(DsGFLotteryEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int insertSelective(DsGFLotteryEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    List<DsGFLotteryEntityWithBLOBs> selectByExampleWithBLOBs(DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    List<DsGFLotteryEntity> selectByExample(DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    DsGFLotteryEntityWithBLOBs selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int updateByExampleSelective(@Param("record") DsGFLotteryEntityWithBLOBs record, @Param("example") DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DsGFLotteryEntityWithBLOBs record, @Param("example") DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int updateByExample(@Param("record") DsGFLotteryEntity record, @Param("example") DsGFLotteryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int updateByPrimaryKeySelective(DsGFLotteryEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int updateByPrimaryKeyWithBLOBs(DsGFLotteryEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_guangfang_lottery
     *
     * @mbggenerated Sat Nov 04 04:21:46 EDT 2017
     */
    int updateByPrimaryKey(DsGFLotteryEntity record);

	DsReportDetail queryTotal(DsGFLotteryEntityExample m_example);

	List<DsReportDetail> queryDetailByMap(Map<String, String> map);

	List<DsReport> queryTotalGroupGameTypeByMap(Map<String, String> map);

	List<DsReport> queryBetTotalByDayNew(DsGFLotteryEntityExample e);
}