package com.ds.report.entity.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ds.report.entity.DsJingdianEntity;
import com.ds.report.entity.DsJingdianEntityExample;
import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;

public interface DsJingdianEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int countByExample(DsJingdianEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int deleteByExample(DsJingdianEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int insert(DsJingdianEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int insertSelective(DsJingdianEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    List<DsJingdianEntity> selectByExample(DsJingdianEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    DsJingdianEntity selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") DsJingdianEntity record, @Param("example") DsJingdianEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int updateByExample(@Param("record") DsJingdianEntity record, @Param("example") DsJingdianEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int updateByPrimaryKeySelective(DsJingdianEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_jingdian_lottery
     *
     * @mbggenerated Sun Dec 11 14:37:25 CST 2016
     */
    int updateByPrimaryKey(DsJingdianEntity record);
    
    
    //查询明细总条数、总投注金额、总有效金额及总输赢金额
    DsReportDetail queryTotal(DsJingdianEntityExample example);
    List<DsReportDetail> queryDetail(DsJingdianEntityExample example);
	List<DsReport> queryBetTotalByDayNew(DsJingdianEntityExample example);
	List<DsReport> queryTotalGroupGameType(DsJingdianEntityExample m_example);
	
	List<DsReportDetail> queryDetailByMap(Map<String, String> map);
	List<DsReport> queryTotalGroupGameTypeByMap(Map<String, String> map);
}