package com.ds.report.entity.mapper;

import com.ds.report.entity.DSLottoBetEntity;
import com.ds.report.entity.DSLottoBetEntityExample;
import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DSLottoBetEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int countByExample(DSLottoBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int deleteByExample(DSLottoBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int insert(DSLottoBetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int insertSelective(DSLottoBetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    List<DSLottoBetEntity> selectByExample(DSLottoBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    DSLottoBetEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int updateByExampleSelective(@Param("record") DSLottoBetEntity record, @Param("example") DSLottoBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int updateByExample(@Param("record") DSLottoBetEntity record, @Param("example") DSLottoBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int updateByPrimaryKeySelective(DSLottoBetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lotto_bet
     *
     * @mbggenerated Fri Sep 11 15:38:15 EDT 2015
     */
    int updateByPrimaryKey(DSLottoBetEntity record);

	DsReportDetail queryTotal(DSLottoBetEntityExample example);

	List<DsReportDetail> queryDetail(DSLottoBetEntityExample example);

	List<DsReport> queryTotalGroupGameType(DSLottoBetEntityExample example);

	/** 按天统计 */
	List<DsReport> queryBetTotalByDayNew(DSLottoBetEntityExample example);
}