package com.ds.report.entity.mapper;

import com.ds.report.entity.DSLotteryBetEntity;
import com.ds.report.entity.DSLotteryBetEntityExample;
import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DSLotteryBetEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int countByExample(DSLotteryBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int deleteByExample(DSLotteryBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int insert(DSLotteryBetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int insertSelective(DSLotteryBetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    List<DSLotteryBetEntity> selectByExample(DSLotteryBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    DSLotteryBetEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int updateByExampleSelective(@Param("record") DSLotteryBetEntity record, @Param("example") DSLotteryBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int updateByExample(@Param("record") DSLotteryBetEntity record, @Param("example") DSLotteryBetEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int updateByPrimaryKeySelective(DSLotteryBetEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lottery_bet
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    int updateByPrimaryKey(DSLotteryBetEntity record);

	DsReportDetail queryTotal(DSLotteryBetEntityExample example);

	List<DsReportDetail> queryDetail(DSLotteryBetEntityExample example);

	List<DsReport> queryTotalGroupGameType(DSLotteryBetEntityExample example);

	/**  按天统计 */
	List<DsReport> queryBetTotalByDayNew(DSLotteryBetEntityExample example);
}