package com.ds.report.entity.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;
import com.ds.report.entity.LMGLiveEntity;
import com.ds.report.entity.LMGLiveEntityExample;
import com.ds.report.entity.LMGLiveEntityWithBLOBs;

public interface LMGLiveEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    long countByExample(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int deleteByExample(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int insert(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int insertSelective(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    List<LMGLiveEntityWithBLOBs> selectByExampleWithBLOBs(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    List<LMGLiveEntity> selectByExample(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    LMGLiveEntityWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") LMGLiveEntityWithBLOBs record, @Param("example") LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LMGLiveEntityWithBLOBs record, @Param("example") LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByExample(@Param("record") LMGLiveEntity record, @Param("example") LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByPrimaryKeySelective(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByPrimaryKey(LMGLiveEntity record);
    
    
  //查询明细总条数、总投注金额、总有效金额及总输赢金额
    DsReportDetail queryTotal(LMGLiveEntityExample example);
    
	List<DsReport> queryTotalGroupGameType(LMGLiveEntityExample example);

    /** 按天统计 */
	List<DsReport> queryBetTotalByDayNew(LMGLiveEntityExample example);

	List<DsReportDetail> queryDetail(LMGLiveEntityExample m_example);
}