package com.ds.report.entity.mapper;

import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;
import com.ds.report.entity.ManniuBetEntity;
import com.ds.report.entity.ManniuBetEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManniuBetEntityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int countByExample(ManniuBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int deleteByExample(ManniuBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int insert(ManniuBetEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int insertSelective(ManniuBetEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */List<ManniuBetEntity> selectByExample(ManniuBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	ManniuBetEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */int updateByExampleSelective(@Param("record") ManniuBetEntity record,@Param("example") ManniuBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */int updateByExample(@Param("record") ManniuBetEntity record,@Param("example") ManniuBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int updateByPrimaryKeySelective(ManniuBetEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_manniu_bet
	 * @mbggenerated  Sun Nov 06 22:39:50 EST 2016
	 */
	int updateByPrimaryKey(ManniuBetEntity record);

	DsReportDetail queryTotal(ManniuBetEntityExample m_example);

	List<DsReportDetail> queryDetail(ManniuBetEntityExample m_example);

	List<DsReport> queryBetTotalByDayNew(ManniuBetEntityExample m_example);

	List<DsReport> queryTotalGroupGameType(ManniuBetEntityExample m_example);
}