package com.ds.report.entity.mapper;

import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;
import com.ds.report.entity.OGLiveEntity;
import com.ds.report.entity.OGLiveEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OGLiveEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int countByExample(OGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int deleteByExample(OGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int insert(OGLiveEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int insertSelective(OGLiveEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    List<OGLiveEntity> selectByExample(OGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    OGLiveEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") OGLiveEntity record, @Param("example") OGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int updateByExample(@Param("record") OGLiveEntity record, @Param("example") OGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int updateByPrimaryKeySelective(OGLiveEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_og_live
     *
     * @mbggenerated Wed Feb 24 15:31:48 CST 2016
     */
    int updateByPrimaryKey(OGLiveEntity record);
    
    List<DsReport> queryBetTotalByDayNew(OGLiveEntityExample m_example);
    
    DsReportDetail queryTotal(OGLiveEntityExample example);

	List<DsReportDetail> queryDetail(OGLiveEntityExample example);
    
    List<DsReport> queryTotalGroupGameType(OGLiveEntityExample example);
}