package com.ds.report.entity.mapper;

import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;
import com.ds.report.entity.VideoGameWager;
import com.ds.report.entity.VideoGameWagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoGameWagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int countByExample(VideoGameWagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int deleteByExample(VideoGameWagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int insert(VideoGameWager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int insertSelective(VideoGameWager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    List<VideoGameWager> selectByExample(VideoGameWagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    VideoGameWager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") VideoGameWager record, @Param("example") VideoGameWagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int updateByExample(@Param("record") VideoGameWager record, @Param("example") VideoGameWagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int updateByPrimaryKeySelective(VideoGameWager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:24 EDT 2015
     */
    int updateByPrimaryKey(VideoGameWager record);

	DsReportDetail queryTotal(VideoGameWagerExample example);

	List<DsReportDetail> queryDetail(VideoGameWagerExample example);

	List<DsReport> queryTotalGroupGameType(VideoGameWagerExample example);

	List<DsReport> queryBetTotalByDayNew(VideoGameWagerExample example);
}