package com.ds.report.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ds.report.entity.DsAgSport;
import com.ds.report.entity.DsAgSportExample;
import com.ds.report.entity.DsReport;
import com.ds.report.entity.DsReportDetail;

public interface DsAgSportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    long countByExample(DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int deleteByExample(DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int insert(DsAgSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int insertSelective(DsAgSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    List<DsAgSport> selectByExampleWithBLOBs(DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    List<DsAgSport> selectByExample(DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    DsAgSport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") DsAgSport record, @Param("example") DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DsAgSport record, @Param("example") DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int updateByExample(@Param("record") DsAgSport record, @Param("example") DsAgSportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int updateByPrimaryKeySelective(DsAgSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DsAgSport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_sport
     *
     * @mbg.generated Mon May 07 10:20:11 CST 2018
     */
    int updateByPrimaryKey(DsAgSport record);
    
    //查询明细总条数、总投注金额、总有效金额及总输赢金额
    DsReportDetail queryTotal(DsAgSportExample example);
    List<DsReportDetail> queryDetail(DsAgSportExample example);

	List<DsReport> queryTotalGroupGameType(DsAgSportExample example);

	/** 按天统计 */
	List<DsReport> queryBetTotalByDayNew(DsAgSportExample example);
}