package com.ds.live.mapper;

import com.ds.live.entity.BBINGameHttpConfig;
import com.ds.live.entity.BBINGameHttpConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BBINGameHttpConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    long countByExample(BBINGameHttpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int deleteByExample(BBINGameHttpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int insert(BBINGameHttpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int insertSelective(BBINGameHttpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    List<BBINGameHttpConfig> selectByExample(BBINGameHttpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    BBINGameHttpConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") BBINGameHttpConfig record, @Param("example") BBINGameHttpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int updateByExample(@Param("record") BBINGameHttpConfig record, @Param("example") BBINGameHttpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int updateByPrimaryKeySelective(BBINGameHttpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_bbin_game_http_config
     *
     * @mbg.generated Mon Nov 27 14:51:43 CST 2017
     */
    int updateByPrimaryKey(BBINGameHttpConfig record);
}