package com.ds.report.entity;

import java.util.Date;

public class DSLotteryBetEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.billno
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Long billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.site_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.username
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.tray
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String tray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.bet_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Date betTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.bet_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String betId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.game_info_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Integer gameInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.game_no
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String gameNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.bet_on
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String betOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.bet_type
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String betType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.odds
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Double odds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.bet_detail
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String betDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.stake_amount
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Double stakeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.valid_stake
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Double validStake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.win_loss
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Double winLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.win_loss_type
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Byte winLossType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.ip
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.create_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lottery_bet.update_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.id
     *
     * @return the value of ds_lottery_bet.id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.id
     *
     * @param id the value for ds_lottery_bet.id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.billno
     *
     * @return the value of ds_lottery_bet.billno
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Long getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.billno
     *
     * @param billno the value for ds_lottery_bet.billno
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setBillno(Long billno) {
        this.billno = billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.site_id
     *
     * @return the value of ds_lottery_bet.site_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.site_id
     *
     * @param siteId the value for ds_lottery_bet.site_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.username
     *
     * @return the value of ds_lottery_bet.username
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.username
     *
     * @param username the value for ds_lottery_bet.username
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.tray
     *
     * @return the value of ds_lottery_bet.tray
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getTray() {
        return tray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.tray
     *
     * @param tray the value for ds_lottery_bet.tray
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setTray(String tray) {
        this.tray = tray == null ? null : tray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.bet_time
     *
     * @return the value of ds_lottery_bet.bet_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Date getBetTime() {
        return betTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.bet_time
     *
     * @param betTime the value for ds_lottery_bet.bet_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setBetTime(Date betTime) {
        this.betTime = betTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.bet_id
     *
     * @return the value of ds_lottery_bet.bet_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getBetId() {
        return betId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.bet_id
     *
     * @param betId the value for ds_lottery_bet.bet_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setBetId(String betId) {
        this.betId = betId == null ? null : betId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.game_info_id
     *
     * @return the value of ds_lottery_bet.game_info_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Integer getGameInfoId() {
        return gameInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.game_info_id
     *
     * @param gameInfoId the value for ds_lottery_bet.game_info_id
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setGameInfoId(Integer gameInfoId) {
        this.gameInfoId = gameInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.game_no
     *
     * @return the value of ds_lottery_bet.game_no
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getGameNo() {
        return gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.game_no
     *
     * @param gameNo the value for ds_lottery_bet.game_no
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setGameNo(String gameNo) {
        this.gameNo = gameNo == null ? null : gameNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.bet_on
     *
     * @return the value of ds_lottery_bet.bet_on
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getBetOn() {
        return betOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.bet_on
     *
     * @param betOn the value for ds_lottery_bet.bet_on
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setBetOn(String betOn) {
        this.betOn = betOn == null ? null : betOn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.bet_type
     *
     * @return the value of ds_lottery_bet.bet_type
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getBetType() {
        return betType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.bet_type
     *
     * @param betType the value for ds_lottery_bet.bet_type
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setBetType(String betType) {
        this.betType = betType == null ? null : betType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.odds
     *
     * @return the value of ds_lottery_bet.odds
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Double getOdds() {
        return odds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.odds
     *
     * @param odds the value for ds_lottery_bet.odds
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setOdds(Double odds) {
        this.odds = odds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.bet_detail
     *
     * @return the value of ds_lottery_bet.bet_detail
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getBetDetail() {
        return betDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.bet_detail
     *
     * @param betDetail the value for ds_lottery_bet.bet_detail
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setBetDetail(String betDetail) {
        this.betDetail = betDetail == null ? null : betDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.stake_amount
     *
     * @return the value of ds_lottery_bet.stake_amount
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Double getStakeAmount() {
        return stakeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.stake_amount
     *
     * @param stakeAmount the value for ds_lottery_bet.stake_amount
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setStakeAmount(Double stakeAmount) {
        this.stakeAmount = stakeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.valid_stake
     *
     * @return the value of ds_lottery_bet.valid_stake
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Double getValidStake() {
        return validStake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.valid_stake
     *
     * @param validStake the value for ds_lottery_bet.valid_stake
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setValidStake(Double validStake) {
        this.validStake = validStake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.win_loss
     *
     * @return the value of ds_lottery_bet.win_loss
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Double getWinLoss() {
        return winLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.win_loss
     *
     * @param winLoss the value for ds_lottery_bet.win_loss
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setWinLoss(Double winLoss) {
        this.winLoss = winLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.win_loss_type
     *
     * @return the value of ds_lottery_bet.win_loss_type
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Byte getWinLossType() {
        return winLossType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.win_loss_type
     *
     * @param winLossType the value for ds_lottery_bet.win_loss_type
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setWinLossType(Byte winLossType) {
        this.winLossType = winLossType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.ip
     *
     * @return the value of ds_lottery_bet.ip
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.ip
     *
     * @param ip the value for ds_lottery_bet.ip
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.create_time
     *
     * @return the value of ds_lottery_bet.create_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.create_time
     *
     * @param createTime the value for ds_lottery_bet.create_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lottery_bet.update_time
     *
     * @return the value of ds_lottery_bet.update_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lottery_bet.update_time
     *
     * @param updateTime the value for ds_lottery_bet.update_time
     *
     * @mbggenerated Sat Sep 12 02:58:41 EDT 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}