package com.ds.report.entity;

public class GameKindOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_game_kind_order.id
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_game_kind_order.game_kind
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	private Integer gameKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_game_kind_order.game_kind_name
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	private String gameKindName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_game_kind_order.order_asc
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	private Integer orderAsc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_game_kind_order.state
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_game_kind_order.id
	 * @return  the value of ds_game_kind_order.id
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_game_kind_order.id
	 * @param id  the value for ds_game_kind_order.id
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_game_kind_order.game_kind
	 * @return  the value of ds_game_kind_order.game_kind
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public Integer getGameKind() {
		return gameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_game_kind_order.game_kind
	 * @param gameKind  the value for ds_game_kind_order.game_kind
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public void setGameKind(Integer gameKind) {
		this.gameKind = gameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_game_kind_order.game_kind_name
	 * @return  the value of ds_game_kind_order.game_kind_name
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public String getGameKindName() {
		return gameKindName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_game_kind_order.game_kind_name
	 * @param gameKindName  the value for ds_game_kind_order.game_kind_name
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public void setGameKindName(String gameKindName) {
		this.gameKindName = gameKindName == null ? null : gameKindName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_game_kind_order.order_asc
	 * @return  the value of ds_game_kind_order.order_asc
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public Integer getOrderAsc() {
		return orderAsc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_game_kind_order.order_asc
	 * @param orderAsc  the value for ds_game_kind_order.order_asc
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public void setOrderAsc(Integer orderAsc) {
		this.orderAsc = orderAsc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_game_kind_order.state
	 * @return  the value of ds_game_kind_order.state
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_game_kind_order.state
	 * @param state  the value for ds_game_kind_order.state
	 * @mbggenerated  Tue Nov 03 16:16:29 CST 2015
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}