package com.ds.report.entity;

import java.math.BigDecimal;
import java.util.Date;

public class VideoGameWager {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.id
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.siteId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Integer siteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.username
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.accountId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String accountid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.transactionId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String transactionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.betAmount
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private BigDecimal betamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.winLose
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private BigDecimal winlose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.commissonAmount
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private BigDecimal commissonamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.winLoseType
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Integer winlosetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.gameKey
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String gamekey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.gameSetId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String gamesetid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.resultTransactionId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String resulttransactionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.money
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private BigDecimal money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.currency
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String currency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.isFinal
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Short isfinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.createTime
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.lastUpdateTime
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Date lastupdatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.flag
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private Integer flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column video_game_wager.memo
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	private String memo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.id
	 * @return  the value of video_game_wager.id
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.id
	 * @param id  the value for video_game_wager.id
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.siteId
	 * @return  the value of video_game_wager.siteId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Integer getSiteid() {
		return siteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.siteId
	 * @param siteid  the value for video_game_wager.siteId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setSiteid(Integer siteid) {
		this.siteid = siteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.username
	 * @return  the value of video_game_wager.username
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.username
	 * @param username  the value for video_game_wager.username
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.accountId
	 * @return  the value of video_game_wager.accountId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getAccountid() {
		return accountid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.accountId
	 * @param accountid  the value for video_game_wager.accountId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setAccountid(String accountid) {
		this.accountid = accountid == null ? null : accountid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.transactionId
	 * @return  the value of video_game_wager.transactionId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getTransactionid() {
		return transactionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.transactionId
	 * @param transactionid  the value for video_game_wager.transactionId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid == null ? null : transactionid
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.betAmount
	 * @return  the value of video_game_wager.betAmount
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public BigDecimal getBetamount() {
		return betamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.betAmount
	 * @param betamount  the value for video_game_wager.betAmount
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setBetamount(BigDecimal betamount) {
		this.betamount = betamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.winLose
	 * @return  the value of video_game_wager.winLose
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public BigDecimal getWinlose() {
		return winlose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.winLose
	 * @param winlose  the value for video_game_wager.winLose
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setWinlose(BigDecimal winlose) {
		this.winlose = winlose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.commissonAmount
	 * @return  the value of video_game_wager.commissonAmount
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public BigDecimal getCommissonamount() {
		return commissonamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.commissonAmount
	 * @param commissonamount  the value for video_game_wager.commissonAmount
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setCommissonamount(BigDecimal commissonamount) {
		this.commissonamount = commissonamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.winLoseType
	 * @return  the value of video_game_wager.winLoseType
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Integer getWinlosetype() {
		return winlosetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.winLoseType
	 * @param winlosetype  the value for video_game_wager.winLoseType
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setWinlosetype(Integer winlosetype) {
		this.winlosetype = winlosetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.gameKey
	 * @return  the value of video_game_wager.gameKey
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getGamekey() {
		return gamekey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.gameKey
	 * @param gamekey  the value for video_game_wager.gameKey
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setGamekey(String gamekey) {
		this.gamekey = gamekey == null ? null : gamekey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.gameSetId
	 * @return  the value of video_game_wager.gameSetId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getGamesetid() {
		return gamesetid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.gameSetId
	 * @param gamesetid  the value for video_game_wager.gameSetId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setGamesetid(String gamesetid) {
		this.gamesetid = gamesetid == null ? null : gamesetid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.resultTransactionId
	 * @return  the value of video_game_wager.resultTransactionId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getResulttransactionid() {
		return resulttransactionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.resultTransactionId
	 * @param resulttransactionid  the value for video_game_wager.resultTransactionId
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setResulttransactionid(String resulttransactionid) {
		this.resulttransactionid = resulttransactionid == null ? null
				: resulttransactionid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.money
	 * @return  the value of video_game_wager.money
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public BigDecimal getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.money
	 * @param money  the value for video_game_wager.money
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.currency
	 * @return  the value of video_game_wager.currency
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.currency
	 * @param currency  the value for video_game_wager.currency
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setCurrency(String currency) {
		this.currency = currency == null ? null : currency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.isFinal
	 * @return  the value of video_game_wager.isFinal
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Short getIsfinal() {
		return isfinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.isFinal
	 * @param isfinal  the value for video_game_wager.isFinal
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setIsfinal(Short isfinal) {
		this.isfinal = isfinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.createTime
	 * @return  the value of video_game_wager.createTime
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.createTime
	 * @param createtime  the value for video_game_wager.createTime
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.lastUpdateTime
	 * @return  the value of video_game_wager.lastUpdateTime
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Date getLastupdatetime() {
		return lastupdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.lastUpdateTime
	 * @param lastupdatetime  the value for video_game_wager.lastUpdateTime
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setLastupdatetime(Date lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.flag
	 * @return  the value of video_game_wager.flag
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.flag
	 * @param flag  the value for video_game_wager.flag
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column video_game_wager.memo
	 * @return  the value of video_game_wager.memo
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column video_game_wager.memo
	 * @param memo  the value for video_game_wager.memo
	 * @mbggenerated  Wed Sep 02 01:48:23 EDT 2015
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}
}