package com.ds.report.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoGameWagerExample {
    protected String orderByClause;
    protected boolean distinct;
    protected Integer page;

	protected Integer pageLimit;
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public VideoGameWagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public Integer getPage() {
		return page;
	}

	public void setPage(Integer page) {
		this.page = page;
	}

	public Integer getPageLimit() {
		return pageLimit;
	}

	public void setPageLimit(Integer pageLimit) {
		this.pageLimit = pageLimit;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNull() {
            addCriterion("siteId is null");
            return (Criteria) this;
        }

        public Criteria andSiteidIsNotNull() {
            addCriterion("siteId is not null");
            return (Criteria) this;
        }

        public Criteria andSiteidEqualTo(Integer value) {
            addCriterion("siteId =", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotEqualTo(Integer value) {
            addCriterion("siteId <>", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThan(Integer value) {
            addCriterion("siteId >", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidGreaterThanOrEqualTo(Integer value) {
            addCriterion("siteId >=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThan(Integer value) {
            addCriterion("siteId <", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidLessThanOrEqualTo(Integer value) {
            addCriterion("siteId <=", value, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidIn(List<Integer> values) {
            addCriterion("siteId in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotIn(List<Integer> values) {
            addCriterion("siteId not in", values, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidBetween(Integer value1, Integer value2) {
            addCriterion("siteId between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andSiteidNotBetween(Integer value1, Integer value2) {
            addCriterion("siteId not between", value1, value2, "siteid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andAccountidIsNull() {
            addCriterion("accountId is null");
            return (Criteria) this;
        }

        public Criteria andAccountidIsNotNull() {
            addCriterion("accountId is not null");
            return (Criteria) this;
        }

        public Criteria andAccountidEqualTo(String value) {
            addCriterion("accountId =", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotEqualTo(String value) {
            addCriterion("accountId <>", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidGreaterThan(String value) {
            addCriterion("accountId >", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidGreaterThanOrEqualTo(String value) {
            addCriterion("accountId >=", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLessThan(String value) {
            addCriterion("accountId <", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLessThanOrEqualTo(String value) {
            addCriterion("accountId <=", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLike(String value) {
            addCriterion("accountId like", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotLike(String value) {
            addCriterion("accountId not like", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidIn(List<String> values) {
            addCriterion("accountId in", values, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotIn(List<String> values) {
            addCriterion("accountId not in", values, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidBetween(String value1, String value2) {
            addCriterion("accountId between", value1, value2, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotBetween(String value1, String value2) {
            addCriterion("accountId not between", value1, value2, "accountid");
            return (Criteria) this;
        }

        public Criteria andTransactionidIsNull() {
            addCriterion("transactionId is null");
            return (Criteria) this;
        }

        public Criteria andTransactionidIsNotNull() {
            addCriterion("transactionId is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionidEqualTo(String value) {
            addCriterion("transactionId =", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotEqualTo(String value) {
            addCriterion("transactionId <>", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidGreaterThan(String value) {
            addCriterion("transactionId >", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidGreaterThanOrEqualTo(String value) {
            addCriterion("transactionId >=", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidLessThan(String value) {
            addCriterion("transactionId <", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidLessThanOrEqualTo(String value) {
            addCriterion("transactionId <=", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidLike(String value) {
            addCriterion("transactionId like", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotLike(String value) {
            addCriterion("transactionId not like", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidIn(List<String> values) {
            addCriterion("transactionId in", values, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotIn(List<String> values) {
            addCriterion("transactionId not in", values, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidBetween(String value1, String value2) {
            addCriterion("transactionId between", value1, value2, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotBetween(String value1, String value2) {
            addCriterion("transactionId not between", value1, value2, "transactionid");
            return (Criteria) this;
        }

        public Criteria andBetamountIsNull() {
            addCriterion("betAmount is null");
            return (Criteria) this;
        }

        public Criteria andBetamountIsNotNull() {
            addCriterion("betAmount is not null");
            return (Criteria) this;
        }

        public Criteria andBetamountEqualTo(BigDecimal value) {
            addCriterion("betAmount =", value, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountNotEqualTo(BigDecimal value) {
            addCriterion("betAmount <>", value, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountGreaterThan(BigDecimal value) {
            addCriterion("betAmount >", value, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("betAmount >=", value, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountLessThan(BigDecimal value) {
            addCriterion("betAmount <", value, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("betAmount <=", value, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountIn(List<BigDecimal> values) {
            addCriterion("betAmount in", values, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountNotIn(List<BigDecimal> values) {
            addCriterion("betAmount not in", values, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betAmount between", value1, value2, "betamount");
            return (Criteria) this;
        }

        public Criteria andBetamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betAmount not between", value1, value2, "betamount");
            return (Criteria) this;
        }

        public Criteria andWinloseIsNull() {
            addCriterion("winLose is null");
            return (Criteria) this;
        }

        public Criteria andWinloseIsNotNull() {
            addCriterion("winLose is not null");
            return (Criteria) this;
        }

        public Criteria andWinloseEqualTo(BigDecimal value) {
            addCriterion("winLose =", value, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseNotEqualTo(BigDecimal value) {
            addCriterion("winLose <>", value, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseGreaterThan(BigDecimal value) {
            addCriterion("winLose >", value, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("winLose >=", value, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseLessThan(BigDecimal value) {
            addCriterion("winLose <", value, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("winLose <=", value, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseIn(List<BigDecimal> values) {
            addCriterion("winLose in", values, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseNotIn(List<BigDecimal> values) {
            addCriterion("winLose not in", values, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("winLose between", value1, value2, "winlose");
            return (Criteria) this;
        }

        public Criteria andWinloseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("winLose not between", value1, value2, "winlose");
            return (Criteria) this;
        }

        public Criteria andCommissonamountIsNull() {
            addCriterion("commissonAmount is null");
            return (Criteria) this;
        }

        public Criteria andCommissonamountIsNotNull() {
            addCriterion("commissonAmount is not null");
            return (Criteria) this;
        }

        public Criteria andCommissonamountEqualTo(BigDecimal value) {
            addCriterion("commissonAmount =", value, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountNotEqualTo(BigDecimal value) {
            addCriterion("commissonAmount <>", value, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountGreaterThan(BigDecimal value) {
            addCriterion("commissonAmount >", value, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("commissonAmount >=", value, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountLessThan(BigDecimal value) {
            addCriterion("commissonAmount <", value, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("commissonAmount <=", value, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountIn(List<BigDecimal> values) {
            addCriterion("commissonAmount in", values, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountNotIn(List<BigDecimal> values) {
            addCriterion("commissonAmount not in", values, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commissonAmount between", value1, value2, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andCommissonamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commissonAmount not between", value1, value2, "commissonamount");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeIsNull() {
            addCriterion("winLoseType is null");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeIsNotNull() {
            addCriterion("winLoseType is not null");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeEqualTo(Integer value) {
            addCriterion("winLoseType =", value, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeNotEqualTo(Integer value) {
            addCriterion("winLoseType <>", value, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeGreaterThan(Integer value) {
            addCriterion("winLoseType >", value, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("winLoseType >=", value, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeLessThan(Integer value) {
            addCriterion("winLoseType <", value, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeLessThanOrEqualTo(Integer value) {
            addCriterion("winLoseType <=", value, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeIn(List<Integer> values) {
            addCriterion("winLoseType in", values, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeNotIn(List<Integer> values) {
            addCriterion("winLoseType not in", values, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeBetween(Integer value1, Integer value2) {
            addCriterion("winLoseType between", value1, value2, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andWinlosetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("winLoseType not between", value1, value2, "winlosetype");
            return (Criteria) this;
        }

        public Criteria andGamekeyIsNull() {
            addCriterion("gameKey is null");
            return (Criteria) this;
        }

        public Criteria andGamekeyIsNotNull() {
            addCriterion("gameKey is not null");
            return (Criteria) this;
        }

        public Criteria andGamekeyEqualTo(String value) {
            addCriterion("gameKey =", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyNotEqualTo(String value) {
            addCriterion("gameKey <>", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyGreaterThan(String value) {
            addCriterion("gameKey >", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyGreaterThanOrEqualTo(String value) {
            addCriterion("gameKey >=", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyLessThan(String value) {
            addCriterion("gameKey <", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyLessThanOrEqualTo(String value) {
            addCriterion("gameKey <=", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyLike(String value) {
            addCriterion("gameKey like", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyNotLike(String value) {
            addCriterion("gameKey not like", value, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyIn(List<String> values) {
            addCriterion("gameKey in", values, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyNotIn(List<String> values) {
            addCriterion("gameKey not in", values, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyBetween(String value1, String value2) {
            addCriterion("gameKey between", value1, value2, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamekeyNotBetween(String value1, String value2) {
            addCriterion("gameKey not between", value1, value2, "gamekey");
            return (Criteria) this;
        }

        public Criteria andGamesetidIsNull() {
            addCriterion("gameSetId is null");
            return (Criteria) this;
        }

        public Criteria andGamesetidIsNotNull() {
            addCriterion("gameSetId is not null");
            return (Criteria) this;
        }

        public Criteria andGamesetidEqualTo(String value) {
            addCriterion("gameSetId =", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidNotEqualTo(String value) {
            addCriterion("gameSetId <>", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidGreaterThan(String value) {
            addCriterion("gameSetId >", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidGreaterThanOrEqualTo(String value) {
            addCriterion("gameSetId >=", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidLessThan(String value) {
            addCriterion("gameSetId <", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidLessThanOrEqualTo(String value) {
            addCriterion("gameSetId <=", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidLike(String value) {
            addCriterion("gameSetId like", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidNotLike(String value) {
            addCriterion("gameSetId not like", value, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidIn(List<String> values) {
            addCriterion("gameSetId in", values, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidNotIn(List<String> values) {
            addCriterion("gameSetId not in", values, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidBetween(String value1, String value2) {
            addCriterion("gameSetId between", value1, value2, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andGamesetidNotBetween(String value1, String value2) {
            addCriterion("gameSetId not between", value1, value2, "gamesetid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidIsNull() {
            addCriterion("resultTransactionId is null");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidIsNotNull() {
            addCriterion("resultTransactionId is not null");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidEqualTo(String value) {
            addCriterion("resultTransactionId =", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidNotEqualTo(String value) {
            addCriterion("resultTransactionId <>", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidGreaterThan(String value) {
            addCriterion("resultTransactionId >", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidGreaterThanOrEqualTo(String value) {
            addCriterion("resultTransactionId >=", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidLessThan(String value) {
            addCriterion("resultTransactionId <", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidLessThanOrEqualTo(String value) {
            addCriterion("resultTransactionId <=", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidLike(String value) {
            addCriterion("resultTransactionId like", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidNotLike(String value) {
            addCriterion("resultTransactionId not like", value, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidIn(List<String> values) {
            addCriterion("resultTransactionId in", values, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidNotIn(List<String> values) {
            addCriterion("resultTransactionId not in", values, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidBetween(String value1, String value2) {
            addCriterion("resultTransactionId between", value1, value2, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andResulttransactionidNotBetween(String value1, String value2) {
            addCriterion("resultTransactionId not between", value1, value2, "resulttransactionid");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("currency is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("currency is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("currency =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("currency <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("currency >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("currency >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("currency <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("currency <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("currency like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("currency not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("currency in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("currency not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("currency between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("currency not between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andIsfinalIsNull() {
            addCriterion("isFinal is null");
            return (Criteria) this;
        }

        public Criteria andIsfinalIsNotNull() {
            addCriterion("isFinal is not null");
            return (Criteria) this;
        }

        public Criteria andIsfinalEqualTo(Short value) {
            addCriterion("isFinal =", value, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalNotEqualTo(Short value) {
            addCriterion("isFinal <>", value, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalGreaterThan(Short value) {
            addCriterion("isFinal >", value, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalGreaterThanOrEqualTo(Short value) {
            addCriterion("isFinal >=", value, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalLessThan(Short value) {
            addCriterion("isFinal <", value, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalLessThanOrEqualTo(Short value) {
            addCriterion("isFinal <=", value, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalIn(List<Short> values) {
            addCriterion("isFinal in", values, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalNotIn(List<Short> values) {
            addCriterion("isFinal not in", values, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalBetween(Short value1, Short value2) {
            addCriterion("isFinal between", value1, value2, "isfinal");
            return (Criteria) this;
        }

        public Criteria andIsfinalNotBetween(Short value1, Short value2) {
            addCriterion("isFinal not between", value1, value2, "isfinal");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNull() {
            addCriterion("lastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNotNull() {
            addCriterion("lastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeEqualTo(Date value) {
            addCriterion("lastUpdateTime =", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotEqualTo(Date value) {
            addCriterion("lastUpdateTime <>", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThan(Date value) {
            addCriterion("lastUpdateTime >", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime >=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThan(Date value) {
            addCriterion("lastUpdateTime <", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime <=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIn(List<Date> values) {
            addCriterion("lastUpdateTime in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotIn(List<Date> values) {
            addCriterion("lastUpdateTime not in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime not between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_game_wager
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 02 01:48:23 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_game_wager
     *
     * @mbggenerated Wed Sep 02 01:48:23 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}