spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://172.19.0.3:3306/game_report
        username: game_report
        password: myPQlliNfN3jaaKttako9Gndimx3gc3GsKatIvkR9SPP11LxzClsIA3cvfaI77jr/k+WphH5tOQ6shXVvzjwKg==
        connectionProperties: config.decrypt=true
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: config,stat
        maxWait: 60000
        maxActive: 20
        initialSize: 1
        minIdle: 1
        validationQuery: select 1
        testWhileIdle: true
        poolPreparedStatements: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        logSlowSql: true

mybatis: 
    mapperLocations: classpath:com/ds/**/*.xml,classpath:com/kg/**/*.xml
    typeAliasesPackage: com.ds

server:
    port: 8086

ag: 
  ftp:
    host: xc.gdcapi.com
    port: 21
    username: CS2.dingtaiyu
    password: JRuDKMqfTd
    path:
      live: /AGIN/
      game: /XIN/
      yoplay: /YOPLAY/
      hunter: /HUNTER/
      sport: /SBTA/
  status:   
    live: true #是否拉取标识
    game: true
    yoplay: true
    hunter: true
    sport: true
  live:
    gamelist: BAC,CBAC,LINK,DT,LBAC,ULPK,SHB,ROU,FT,BJ,NN,SBAC,ZJH,BF #记录ag视讯的所有游戏

telegram:
  message:
    bot: 604355646:AAG1mCGGvj_nv6BbgHYrM0E0-3_SzpthPRg
    groupid: -286022000
    
      
logging:
  level:
     com.ds : debug
