package com.ds.lottery.mapper;

import com.ds.lottery.entity.GFLotteryEntity;
import com.ds.lottery.entity.GFLotteryEntityExample;
import com.ds.lottery.entity.GFLotteryEntityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GFLotteryEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int countByExample(GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int deleteByExample(GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int deleteByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int insert(GFLotteryEntityWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int insertSelective(GFLotteryEntityWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	List<GFLotteryEntityWithBLOBs> selectByExampleWithBLOBs(
			GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	List<GFLotteryEntity> selectByExample(GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	GFLotteryEntityWithBLOBs selectByPrimaryKey(Long tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int updateByExampleSelective(
			@Param("record") GFLotteryEntityWithBLOBs record,
			@Param("example") GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int updateByExampleWithBLOBs(
			@Param("record") GFLotteryEntityWithBLOBs record,
			@Param("example") GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int updateByExample(@Param("record") GFLotteryEntity record,
			@Param("example") GFLotteryEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int updateByPrimaryKeySelective(GFLotteryEntityWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int updateByPrimaryKeyWithBLOBs(GFLotteryEntityWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_guangfang_lottery
	 * @mbggenerated  Mon Oct 23 05:41:54 EDT 2017
	 */
	int updateByPrimaryKey(GFLotteryEntity record);
}