spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://172.19.0.3:3306/game_report
        username: game_report
        password: myPQlliNfN3jaaKttako9Gndimx3gc3GsKatIvkR9SPP11LxzClsIA3cvfaI77jr/k+WphH5tOQ6shXVvzjwKg==
        connectionProperties: config.decrypt=true
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: config,stat
        maxWait: 60000
        maxActive: 20
        initialSize: 1
        minIdle: 1
        validationQuery: select 1
        testWhileIdle: true
        poolPreparedStatements: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        logSlowSql: true

mybatis: 
    mapperLocations: classpath:com/ds/**/*.xml,classpath:com/kg/**/*.xml
    typeAliasesPackage: com.ds.lmg

server:
    port: 8092