spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://10.200.201.14:3306/game_report
        username: game_report
        password: Fh3bAMhLRFjzGpCGXZHw25bzvonfN4VUiTE9hN46NQI7yS6bD4OiaK+Eegsg8yhlAepNw028uQwz5v7pbhS1SQ==
        connectionProperties: config.decrypt=true
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: config,stat
        maxWait: 60000
        maxActive: 20
        initialSize: 1
        minIdle: 1
        validationQuery: select 1
        testWhileIdle: true
        poolPreparedStatements: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: false
        testOnReturn: false
        logSlowSql: true

mybatis: 
    mapperLocations: classpath:com/ds/**/*.xml,classpath:com/kg/**/*.xml
    typeAliasesPackage: com.ds.lmg

server:
    port: 8080