package com.kg.live.mapper;

import com.kg.live.entity.AgFtpConfig;
import com.kg.live.entity.AgFtpConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgFtpConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int countByExample(AgFtpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int deleteByExample(AgFtpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int insert(AgFtpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int insertSelective(AgFtpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    List<AgFtpConfig> selectByExample(AgFtpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    AgFtpConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") AgFtpConfig record, @Param("example") AgFtpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int updateByExample(@Param("record") AgFtpConfig record, @Param("example") AgFtpConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int updateByPrimaryKeySelective(AgFtpConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ag_ftp_config
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    int updateByPrimaryKey(AgFtpConfig record);
}