package com.kg.live.mapper;

import com.kg.live.entity.BeijingLottoEntity;
import com.kg.live.entity.BeijingLottoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BeijingLottoEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int countByExample(BeijingLottoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int deleteByExample(BeijingLottoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int deleteByPrimaryKey(String billno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int insert(BeijingLottoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int insertSelective(BeijingLottoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	List<BeijingLottoEntity> selectByExample(BeijingLottoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	BeijingLottoEntity selectByPrimaryKey(String billno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int updateByExampleSelective(@Param("record") BeijingLottoEntity record,
			@Param("example") BeijingLottoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int updateByExample(@Param("record") BeijingLottoEntity record,
			@Param("example") BeijingLottoEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int updateByPrimaryKeySelective(BeijingLottoEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_beijing_lotto
	 * @mbggenerated  Fri Jun 03 22:02:11 ADT 2016
	 */
	int updateByPrimaryKey(BeijingLottoEntity record);
}