package com.kg.live.mapper;

import com.kg.live.entity.DsAgFileRecord;
import com.kg.live.entity.DsAgFileRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsAgFileRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    long countByExample(DsAgFileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int deleteByExample(DsAgFileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int insert(DsAgFileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int insertSelective(DsAgFileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    List<DsAgFileRecord> selectByExample(DsAgFileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    DsAgFileRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") DsAgFileRecord record, @Param("example") DsAgFileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int updateByExample(@Param("record") DsAgFileRecord record, @Param("example") DsAgFileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int updateByPrimaryKeySelective(DsAgFileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_ag_file_record
     *
     * @mbg.generated Mon May 14 10:13:37 CST 2018
     */
    int updateByPrimaryKey(DsAgFileRecord record);
}