package com.kg.live.mapper;

import com.kg.live.entity.DsAgHunterReport;
import com.kg.live.entity.DsAgHunterReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsAgHunterReportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int countByExample(DsAgHunterReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int deleteByExample(DsAgHunterReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int insert(DsAgHunterReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int insertSelective(DsAgHunterReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	List<DsAgHunterReport> selectByExample(DsAgHunterReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	DsAgHunterReport selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int updateByExampleSelective(@Param("record") DsAgHunterReport record,
			@Param("example") DsAgHunterReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int updateByExample(@Param("record") DsAgHunterReport record,
			@Param("example") DsAgHunterReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int updateByPrimaryKeySelective(DsAgHunterReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_aghunter_report
	 * @mbggenerated  Wed Jul 26 05:13:06 EDT 2017
	 */
	int updateByPrimaryKey(DsAgHunterReport record);
}