package com.kg.live.mapper;

import com.kg.live.entity.DsGameType;
import com.kg.live.entity.DsGameTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsGameTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int countByExample(DsGameTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int deleteByExample(DsGameTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int insert(DsGameType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int insertSelective(DsGameType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    List<DsGameType> selectByExample(DsGameTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    DsGameType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") DsGameType record, @Param("example") DsGameTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int updateByExample(@Param("record") DsGameType record, @Param("example") DsGameTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int updateByPrimaryKeySelective(DsGameType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_game_type
     *
     * @mbggenerated Mon Nov 02 13:46:13 CST 2015
     */
    int updateByPrimaryKey(DsGameType record);
}