package com.kg.live.mapper;

import com.kg.live.entity.DsLottoBetEntity;
import com.kg.live.entity.DsLottoBetEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import java.math.BigInteger;

public interface DsLottoBetEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int countByExample(DsLottoBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int deleteByExample(DsLottoBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int deleteByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int insert(DsLottoBetEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int insertSelective(DsLottoBetEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	List<DsLottoBetEntity> selectByExample(DsLottoBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	DsLottoBetEntity selectByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int updateByExampleSelective(@Param("record") DsLottoBetEntity record,
			@Param("example") DsLottoBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int updateByExample(@Param("record") DsLottoBetEntity record,
			@Param("example") DsLottoBetEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int updateByPrimaryKeySelective(DsLottoBetEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_lotto_bet
	 * @mbggenerated  Sat Sep 05 21:22:13 ADT 2015
	 */
	int updateByPrimaryKey(DsLottoBetEntity record);
}