package com.kg.live.mapper;

import com.kg.live.entity.DsMgGameDetail;
import com.kg.live.entity.DsMgGameDetailExample;
import com.kg.live.entity.DsMgGameDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsMgGameDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    long countByExample(DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int deleteByExample(DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int insert(DsMgGameDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int insertSelective(DsMgGameDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    List<DsMgGameDetailWithBLOBs> selectByExampleWithBLOBs(DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    List<DsMgGameDetail> selectByExample(DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    DsMgGameDetailWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") DsMgGameDetailWithBLOBs record, @Param("example") DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DsMgGameDetailWithBLOBs record, @Param("example") DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int updateByExample(@Param("record") DsMgGameDetail record, @Param("example") DsMgGameDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int updateByPrimaryKeySelective(DsMgGameDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DsMgGameDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_mg_game_detail
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    int updateByPrimaryKey(DsMgGameDetail record);
}