package com.kg.live.mapper;

import com.kg.live.entity.FenfenLottoSaibao;
import com.kg.live.entity.FenfenLottoSaibaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FenfenLottoSaibaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int countByExample(FenfenLottoSaibaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int deleteByExample(FenfenLottoSaibaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int insert(FenfenLottoSaibao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int insertSelective(FenfenLottoSaibao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    List<FenfenLottoSaibao> selectByExample(FenfenLottoSaibaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    FenfenLottoSaibao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") FenfenLottoSaibao record, @Param("example") FenfenLottoSaibaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int updateByExample(@Param("record") FenfenLottoSaibao record, @Param("example") FenfenLottoSaibaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int updateByPrimaryKeySelective(FenfenLottoSaibao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_fenfen_saibao
     *
     * @mbggenerated Sat Nov 07 16:29:05 CST 2015
     */
    int updateByPrimaryKey(FenfenLottoSaibao record);
}