package com.kg.live.mapper;

import com.kg.live.entity.LMGLiveEntity;
import com.kg.live.entity.LMGLiveEntityExample;
import com.kg.live.entity.LMGLiveEntityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LMGLiveEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    long countByExample(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int deleteByExample(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int insert(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int insertSelective(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    List<LMGLiveEntityWithBLOBs> selectByExampleWithBLOBs(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    List<LMGLiveEntity> selectByExample(LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    LMGLiveEntityWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") LMGLiveEntityWithBLOBs record, @Param("example") LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LMGLiveEntityWithBLOBs record, @Param("example") LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByExample(@Param("record") LMGLiveEntity record, @Param("example") LMGLiveEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByPrimaryKeySelective(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LMGLiveEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_lmg_live
     *
     * @mbg.generated Tue Mar 13 11:35:40 CST 2018
     */
    int updateByPrimaryKey(LMGLiveEntity record);
}