package com.kg.live.mapper;

import com.kg.live.entity.LotteryInfoEntity;
import com.kg.live.entity.LotteryInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LotteryInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    int countByExample(LotteryInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    int deleteByExample(LotteryInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    int insert(LotteryInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    int insertSelective(LotteryInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    List<LotteryInfoEntity> selectByExample(LotteryInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") LotteryInfoEntity record, @Param("example") LotteryInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_info
     *
     * @mbggenerated Fri Dec 09 10:54:05 CST 2016
     */
    int updateByExample(@Param("record") LotteryInfoEntity record, @Param("example") LotteryInfoEntityExample example);
}