package com.kg.live.mapper;

import com.kg.live.entity.MGGameConfig;
import com.kg.live.entity.MGGameConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MGGameConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int countByExample(MGGameConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int deleteByExample(MGGameConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int insert(MGGameConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int insertSelective(MGGameConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	List<MGGameConfig> selectByExample(MGGameConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	MGGameConfig selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int updateByExampleSelective(@Param("record") MGGameConfig record,
			@Param("example") MGGameConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int updateByExample(@Param("record") MGGameConfig record,
			@Param("example") MGGameConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int updateByPrimaryKeySelective(MGGameConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game_config
	 * @mbggenerated  Mon Jul 18 13:11:35 CST 2016
	 */
	int updateByPrimaryKey(MGGameConfig record);
}