package com.kg.live.mapper;

import com.kg.live.entity.MGGameEntity;
import com.kg.live.entity.MGGameEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MGGameEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int countByExample(MGGameEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int deleteByExample(MGGameEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int insert(MGGameEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int insertSelective(MGGameEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	List<MGGameEntity> selectByExample(MGGameEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	MGGameEntity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") MGGameEntity record,
			@Param("example") MGGameEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int updateByExample(@Param("record") MGGameEntity record,
			@Param("example") MGGameEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int updateByPrimaryKeySelective(MGGameEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_mg_game
	 * @mbggenerated  Tue Jul 19 13:29:06 CST 2016
	 */
	int updateByPrimaryKey(MGGameEntity record);
}