package com.kg.live.mapper;

import com.kg.live.entity.TotalReportConfig;
import com.kg.live.entity.TotalReportConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.kg.live.entity.TotalReportConfigWithBLOBs;

public interface TotalReportConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int countByExample(TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int deleteByExample(TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int insert(TotalReportConfigWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int insertSelective(TotalReportConfigWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	List<TotalReportConfigWithBLOBs> selectByExampleWithBLOBs(
			TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	List<TotalReportConfig> selectByExample(TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	TotalReportConfigWithBLOBs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int updateByExampleSelective(
			@Param("record") TotalReportConfigWithBLOBs record,
			@Param("example") TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int updateByExampleWithBLOBs(
			@Param("record") TotalReportConfigWithBLOBs record,
			@Param("example") TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int updateByExample(@Param("record") TotalReportConfig record,
			@Param("example") TotalReportConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int updateByPrimaryKeySelective(TotalReportConfigWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(TotalReportConfigWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_total_report_config
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	int updateByPrimaryKey(TotalReportConfig record);
}