package com.kg.live.mapper;

import com.kg.live.entity.XianggangLottoEntity;
import com.kg.live.entity.XianggangLottoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XianggangLottoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int countByExample(XianggangLottoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int deleteByExample(XianggangLottoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int deleteByPrimaryKey(String billno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int insert(XianggangLottoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int insertSelective(XianggangLottoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    List<XianggangLottoEntity> selectByExample(XianggangLottoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    XianggangLottoEntity selectByPrimaryKey(String billno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int updateByExampleSelective(@Param("record") XianggangLottoEntity record, @Param("example") XianggangLottoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int updateByExample(@Param("record") XianggangLottoEntity record, @Param("example") XianggangLottoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int updateByPrimaryKeySelective(XianggangLottoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_xianggang_lotto
     *
     * @mbggenerated Wed Jun 22 10:48:14 ADT 2016
     */
    int updateByPrimaryKey(XianggangLottoEntity record);
}