package com.kg.live.mapper;

import com.kg.live.entity.XiaoyuCheckId;
import com.kg.live.entity.XiaoyuCheckIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XiaoyuCheckIdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int countByExample(XiaoyuCheckIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int deleteByExample(XiaoyuCheckIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int insert(XiaoyuCheckId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int insertSelective(XiaoyuCheckId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	List<XiaoyuCheckId> selectByExample(XiaoyuCheckIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	XiaoyuCheckId selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int updateByExampleSelective(@Param("record") XiaoyuCheckId record,
			@Param("example") XiaoyuCheckIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int updateByExample(@Param("record") XiaoyuCheckId record,
			@Param("example") XiaoyuCheckIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int updateByPrimaryKeySelective(XiaoyuCheckId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_xiaoyu_check_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	int updateByPrimaryKey(XiaoyuCheckId record);
}