package com.kg.live.entity;

public class AgFtpConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.id
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.ag_agent_name
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private String agAgentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.ftp_url
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private String ftpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.ftp_username
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private String ftpUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.ftp_password
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private String ftpPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.ftp_port
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private Integer ftpPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.ftp_path
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private String ftpPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ag_ftp_config.state
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.id
     *
     * @return the value of ag_ftp_config.id
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.id
     *
     * @param id the value for ag_ftp_config.id
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.ag_agent_name
     *
     * @return the value of ag_ftp_config.ag_agent_name
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public String getAgAgentName() {
        return agAgentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.ag_agent_name
     *
     * @param agAgentName the value for ag_ftp_config.ag_agent_name
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setAgAgentName(String agAgentName) {
        this.agAgentName = agAgentName == null ? null : agAgentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.ftp_url
     *
     * @return the value of ag_ftp_config.ftp_url
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public String getFtpUrl() {
        return ftpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.ftp_url
     *
     * @param ftpUrl the value for ag_ftp_config.ftp_url
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setFtpUrl(String ftpUrl) {
        this.ftpUrl = ftpUrl == null ? null : ftpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.ftp_username
     *
     * @return the value of ag_ftp_config.ftp_username
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public String getFtpUsername() {
        return ftpUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.ftp_username
     *
     * @param ftpUsername the value for ag_ftp_config.ftp_username
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setFtpUsername(String ftpUsername) {
        this.ftpUsername = ftpUsername == null ? null : ftpUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.ftp_password
     *
     * @return the value of ag_ftp_config.ftp_password
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public String getFtpPassword() {
        return ftpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.ftp_password
     *
     * @param ftpPassword the value for ag_ftp_config.ftp_password
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setFtpPassword(String ftpPassword) {
        this.ftpPassword = ftpPassword == null ? null : ftpPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.ftp_port
     *
     * @return the value of ag_ftp_config.ftp_port
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public Integer getFtpPort() {
        return ftpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.ftp_port
     *
     * @param ftpPort the value for ag_ftp_config.ftp_port
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setFtpPort(Integer ftpPort) {
        this.ftpPort = ftpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.ftp_path
     *
     * @return the value of ag_ftp_config.ftp_path
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public String getFtpPath() {
        return ftpPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.ftp_path
     *
     * @param ftpPath the value for ag_ftp_config.ftp_path
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setFtpPath(String ftpPath) {
        this.ftpPath = ftpPath == null ? null : ftpPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ag_ftp_config.state
     *
     * @return the value of ag_ftp_config.state
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ag_ftp_config.state
     *
     * @param state the value for ag_ftp_config.state
     *
     * @mbggenerated Fri Jan 01 15:12:17 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }
}