package com.kg.live.entity;

import java.util.Date;

public class BbinPageRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_bbin_page_record.id
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_bbin_page_record.site_id
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_bbin_page_record.game_kind
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	private Integer gameKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_bbin_page_record.page
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	private Integer page;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_bbin_page_record.date
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	private String date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_bbin_page_record.id
	 * @return  the value of ds_bbin_page_record.id
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_bbin_page_record.id
	 * @param id  the value for ds_bbin_page_record.id
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_bbin_page_record.site_id
	 * @return  the value of ds_bbin_page_record.site_id
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_bbin_page_record.site_id
	 * @param siteId  the value for ds_bbin_page_record.site_id
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_bbin_page_record.game_kind
	 * @return  the value of ds_bbin_page_record.game_kind
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public Integer getGameKind() {
		return gameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_bbin_page_record.game_kind
	 * @param gameKind  the value for ds_bbin_page_record.game_kind
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public void setGameKind(Integer gameKind) {
		this.gameKind = gameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_bbin_page_record.page
	 * @return  the value of ds_bbin_page_record.page
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public Integer getPage() {
		return page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_bbin_page_record.page
	 * @param page  the value for ds_bbin_page_record.page
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public void setPage(Integer page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_bbin_page_record.date
	 * @return  the value of ds_bbin_page_record.date
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_bbin_page_record.date
	 * @param date  the value for ds_bbin_page_record.date
	 * @mbggenerated  Fri Dec 08 15:21:33 CST 2017
	 */
	public void setDate(String date) {
		this.date = date == null ? null : date.trim();
	}

	private String agent;
	
	public String getAgent() {
		return agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}
}