package com.kg.live.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DsJPgameEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.site_id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.wagersid
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String wagersid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.jptypeid
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String jptypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.playname
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String playname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.username
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.wagersdate
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private Date wagersdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.jpamount
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private BigDecimal jpamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.agents
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String agents;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.world
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String world;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.corprator
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String corprator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.superior
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String superior;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.admin
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String admin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.live_id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private Integer liveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.live_name
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private String liveName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.create_time
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_jpgame.update_time
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.id
	 * @return  the value of ds_jpgame.id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.id
	 * @param id  the value for ds_jpgame.id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.site_id
	 * @return  the value of ds_jpgame.site_id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.site_id
	 * @param siteId  the value for ds_jpgame.site_id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.wagersid
	 * @return  the value of ds_jpgame.wagersid
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getWagersid() {
		return wagersid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.wagersid
	 * @param wagersid  the value for ds_jpgame.wagersid
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setWagersid(String wagersid) {
		this.wagersid = wagersid == null ? null : wagersid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.jptypeid
	 * @return  the value of ds_jpgame.jptypeid
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getJptypeid() {
		return jptypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.jptypeid
	 * @param jptypeid  the value for ds_jpgame.jptypeid
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setJptypeid(String jptypeid) {
		this.jptypeid = jptypeid == null ? null : jptypeid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.playname
	 * @return  the value of ds_jpgame.playname
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getPlayname() {
		return playname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.playname
	 * @param playname  the value for ds_jpgame.playname
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setPlayname(String playname) {
		this.playname = playname == null ? null : playname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.username
	 * @return  the value of ds_jpgame.username
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.username
	 * @param username  the value for ds_jpgame.username
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.wagersdate
	 * @return  the value of ds_jpgame.wagersdate
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public Date getWagersdate() {
		return wagersdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.wagersdate
	 * @param wagersdate  the value for ds_jpgame.wagersdate
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setWagersdate(Date wagersdate) {
		this.wagersdate = wagersdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.jpamount
	 * @return  the value of ds_jpgame.jpamount
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public BigDecimal getJpamount() {
		return jpamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.jpamount
	 * @param jpamount  the value for ds_jpgame.jpamount
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setJpamount(BigDecimal jpamount) {
		this.jpamount = jpamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.agents
	 * @return  the value of ds_jpgame.agents
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getAgents() {
		return agents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.agents
	 * @param agents  the value for ds_jpgame.agents
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setAgents(String agents) {
		this.agents = agents == null ? null : agents.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.world
	 * @return  the value of ds_jpgame.world
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getWorld() {
		return world;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.world
	 * @param world  the value for ds_jpgame.world
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setWorld(String world) {
		this.world = world == null ? null : world.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.corprator
	 * @return  the value of ds_jpgame.corprator
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getCorprator() {
		return corprator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.corprator
	 * @param corprator  the value for ds_jpgame.corprator
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setCorprator(String corprator) {
		this.corprator = corprator == null ? null : corprator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.superior
	 * @return  the value of ds_jpgame.superior
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getSuperior() {
		return superior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.superior
	 * @param superior  the value for ds_jpgame.superior
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setSuperior(String superior) {
		this.superior = superior == null ? null : superior.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.admin
	 * @return  the value of ds_jpgame.admin
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getAdmin() {
		return admin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.admin
	 * @param admin  the value for ds_jpgame.admin
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setAdmin(String admin) {
		this.admin = admin == null ? null : admin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.live_id
	 * @return  the value of ds_jpgame.live_id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public Integer getLiveId() {
		return liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.live_id
	 * @param liveId  the value for ds_jpgame.live_id
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setLiveId(Integer liveId) {
		this.liveId = liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.live_name
	 * @return  the value of ds_jpgame.live_name
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public String getLiveName() {
		return liveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.live_name
	 * @param liveName  the value for ds_jpgame.live_name
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setLiveName(String liveName) {
		this.liveName = liveName == null ? null : liveName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.create_time
	 * @return  the value of ds_jpgame.create_time
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.create_time
	 * @param createTime  the value for ds_jpgame.create_time
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_jpgame.update_time
	 * @return  the value of ds_jpgame.update_time
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_jpgame.update_time
	 * @param updateTime  the value for ds_jpgame.update_time
	 * @mbggenerated  Thu Jul 16 17:27:34 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}