package com.kg.live.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DsMgGameDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.siteId
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Integer siteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.username
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.playername
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String playername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.hor_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String horKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.bet_col_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String betColId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.win_lose_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Integer winLoseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.hor_ne_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String horNeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.mbr_ne_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String mbrNeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.bet_trans_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String betTransKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.game_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String gameKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.game_code
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String gameCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.product
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String product;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.transaction_timestamp
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Long transactionTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.transaction_timestamp_date
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Date transactionTimestampDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.validate_amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private BigDecimal validateAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.payoff
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private BigDecimal payoff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.mbr_code
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String mbrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.mbr_alias
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String mbrAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.game_poker_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String gamePokerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.ref_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String refType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.ref_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String refKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.after_tx_wallet_amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private BigDecimal afterTxWalletAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.mgs_game_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String mgsGameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.mgs_action_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String mgsActionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.clrng_amnt
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private BigDecimal clrngAmnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.game_platform_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String gamePlatformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.create_time
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.last_update_time
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_mg_game_detail.memo
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.id
     *
     * @return the value of ds_mg_game_detail.id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.id
     *
     * @param id the value for ds_mg_game_detail.id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.siteId
     *
     * @return the value of ds_mg_game_detail.siteId
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.siteId
     *
     * @param siteid the value for ds_mg_game_detail.siteId
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.username
     *
     * @return the value of ds_mg_game_detail.username
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.username
     *
     * @param username the value for ds_mg_game_detail.username
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.playername
     *
     * @return the value of ds_mg_game_detail.playername
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getPlayername() {
        return playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.playername
     *
     * @param playername the value for ds_mg_game_detail.playername
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setPlayername(String playername) {
        this.playername = playername == null ? null : playername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.hor_key
     *
     * @return the value of ds_mg_game_detail.hor_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getHorKey() {
        return horKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.hor_key
     *
     * @param horKey the value for ds_mg_game_detail.hor_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setHorKey(String horKey) {
        this.horKey = horKey == null ? null : horKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.bet_col_id
     *
     * @return the value of ds_mg_game_detail.bet_col_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getBetColId() {
        return betColId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.bet_col_id
     *
     * @param betColId the value for ds_mg_game_detail.bet_col_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setBetColId(String betColId) {
        this.betColId = betColId == null ? null : betColId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.win_lose_type
     *
     * @return the value of ds_mg_game_detail.win_lose_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Integer getWinLoseType() {
        return winLoseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.win_lose_type
     *
     * @param winLoseType the value for ds_mg_game_detail.win_lose_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setWinLoseType(Integer winLoseType) {
        this.winLoseType = winLoseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.hor_ne_key
     *
     * @return the value of ds_mg_game_detail.hor_ne_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getHorNeKey() {
        return horNeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.hor_ne_key
     *
     * @param horNeKey the value for ds_mg_game_detail.hor_ne_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setHorNeKey(String horNeKey) {
        this.horNeKey = horNeKey == null ? null : horNeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.mbr_ne_key
     *
     * @return the value of ds_mg_game_detail.mbr_ne_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getMbrNeKey() {
        return mbrNeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.mbr_ne_key
     *
     * @param mbrNeKey the value for ds_mg_game_detail.mbr_ne_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setMbrNeKey(String mbrNeKey) {
        this.mbrNeKey = mbrNeKey == null ? null : mbrNeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.bet_trans_key
     *
     * @return the value of ds_mg_game_detail.bet_trans_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getBetTransKey() {
        return betTransKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.bet_trans_key
     *
     * @param betTransKey the value for ds_mg_game_detail.bet_trans_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setBetTransKey(String betTransKey) {
        this.betTransKey = betTransKey == null ? null : betTransKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.game_key
     *
     * @return the value of ds_mg_game_detail.game_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getGameKey() {
        return gameKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.game_key
     *
     * @param gameKey the value for ds_mg_game_detail.game_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setGameKey(String gameKey) {
        this.gameKey = gameKey == null ? null : gameKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.game_code
     *
     * @return the value of ds_mg_game_detail.game_code
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getGameCode() {
        return gameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.game_code
     *
     * @param gameCode the value for ds_mg_game_detail.game_code
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setGameCode(String gameCode) {
        this.gameCode = gameCode == null ? null : gameCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.type
     *
     * @return the value of ds_mg_game_detail.type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.type
     *
     * @param type the value for ds_mg_game_detail.type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.product
     *
     * @return the value of ds_mg_game_detail.product
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.product
     *
     * @param product the value for ds_mg_game_detail.product
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.transaction_timestamp
     *
     * @return the value of ds_mg_game_detail.transaction_timestamp
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Long getTransactionTimestamp() {
        return transactionTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.transaction_timestamp
     *
     * @param transactionTimestamp the value for ds_mg_game_detail.transaction_timestamp
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setTransactionTimestamp(Long transactionTimestamp) {
        this.transactionTimestamp = transactionTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.transaction_timestamp_date
     *
     * @return the value of ds_mg_game_detail.transaction_timestamp_date
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Date getTransactionTimestampDate() {
        return transactionTimestampDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.transaction_timestamp_date
     *
     * @param transactionTimestampDate the value for ds_mg_game_detail.transaction_timestamp_date
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setTransactionTimestampDate(Date transactionTimestampDate) {
        this.transactionTimestampDate = transactionTimestampDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.amount
     *
     * @return the value of ds_mg_game_detail.amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.amount
     *
     * @param amount the value for ds_mg_game_detail.amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.validate_amount
     *
     * @return the value of ds_mg_game_detail.validate_amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public BigDecimal getValidateAmount() {
        return validateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.validate_amount
     *
     * @param validateAmount the value for ds_mg_game_detail.validate_amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setValidateAmount(BigDecimal validateAmount) {
        this.validateAmount = validateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.payoff
     *
     * @return the value of ds_mg_game_detail.payoff
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public BigDecimal getPayoff() {
        return payoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.payoff
     *
     * @param payoff the value for ds_mg_game_detail.payoff
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setPayoff(BigDecimal payoff) {
        this.payoff = payoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.mbr_code
     *
     * @return the value of ds_mg_game_detail.mbr_code
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getMbrCode() {
        return mbrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.mbr_code
     *
     * @param mbrCode the value for ds_mg_game_detail.mbr_code
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setMbrCode(String mbrCode) {
        this.mbrCode = mbrCode == null ? null : mbrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.mbr_alias
     *
     * @return the value of ds_mg_game_detail.mbr_alias
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getMbrAlias() {
        return mbrAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.mbr_alias
     *
     * @param mbrAlias the value for ds_mg_game_detail.mbr_alias
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setMbrAlias(String mbrAlias) {
        this.mbrAlias = mbrAlias == null ? null : mbrAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.game_poker_type
     *
     * @return the value of ds_mg_game_detail.game_poker_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getGamePokerType() {
        return gamePokerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.game_poker_type
     *
     * @param gamePokerType the value for ds_mg_game_detail.game_poker_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setGamePokerType(String gamePokerType) {
        this.gamePokerType = gamePokerType == null ? null : gamePokerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.ref_type
     *
     * @return the value of ds_mg_game_detail.ref_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.ref_type
     *
     * @param refType the value for ds_mg_game_detail.ref_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setRefType(String refType) {
        this.refType = refType == null ? null : refType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.ref_key
     *
     * @return the value of ds_mg_game_detail.ref_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getRefKey() {
        return refKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.ref_key
     *
     * @param refKey the value for ds_mg_game_detail.ref_key
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setRefKey(String refKey) {
        this.refKey = refKey == null ? null : refKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.after_tx_wallet_amount
     *
     * @return the value of ds_mg_game_detail.after_tx_wallet_amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public BigDecimal getAfterTxWalletAmount() {
        return afterTxWalletAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.after_tx_wallet_amount
     *
     * @param afterTxWalletAmount the value for ds_mg_game_detail.after_tx_wallet_amount
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setAfterTxWalletAmount(BigDecimal afterTxWalletAmount) {
        this.afterTxWalletAmount = afterTxWalletAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.mgs_game_id
     *
     * @return the value of ds_mg_game_detail.mgs_game_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getMgsGameId() {
        return mgsGameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.mgs_game_id
     *
     * @param mgsGameId the value for ds_mg_game_detail.mgs_game_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setMgsGameId(String mgsGameId) {
        this.mgsGameId = mgsGameId == null ? null : mgsGameId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.mgs_action_id
     *
     * @return the value of ds_mg_game_detail.mgs_action_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getMgsActionId() {
        return mgsActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.mgs_action_id
     *
     * @param mgsActionId the value for ds_mg_game_detail.mgs_action_id
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setMgsActionId(String mgsActionId) {
        this.mgsActionId = mgsActionId == null ? null : mgsActionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.clrng_amnt
     *
     * @return the value of ds_mg_game_detail.clrng_amnt
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public BigDecimal getClrngAmnt() {
        return clrngAmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.clrng_amnt
     *
     * @param clrngAmnt the value for ds_mg_game_detail.clrng_amnt
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setClrngAmnt(BigDecimal clrngAmnt) {
        this.clrngAmnt = clrngAmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.game_platform_type
     *
     * @return the value of ds_mg_game_detail.game_platform_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getGamePlatformType() {
        return gamePlatformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.game_platform_type
     *
     * @param gamePlatformType the value for ds_mg_game_detail.game_platform_type
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setGamePlatformType(String gamePlatformType) {
        this.gamePlatformType = gamePlatformType == null ? null : gamePlatformType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.create_time
     *
     * @return the value of ds_mg_game_detail.create_time
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.create_time
     *
     * @param createTime the value for ds_mg_game_detail.create_time
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.last_update_time
     *
     * @return the value of ds_mg_game_detail.last_update_time
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.last_update_time
     *
     * @param lastUpdateTime the value for ds_mg_game_detail.last_update_time
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_mg_game_detail.memo
     *
     * @return the value of ds_mg_game_detail.memo
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_mg_game_detail.memo
     *
     * @param memo the value for ds_mg_game_detail.memo
     *
     * @mbg.generated Sat May 05 16:11:45 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}