package com.kg.live.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DsReportEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.username
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.bet_count
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Integer betCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.betamount
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal betamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.winlose
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal winlose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.validamount
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal validamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.site_id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Integer siteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.live_id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Byte liveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.live_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String liveName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.game_kind
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Integer gameKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.game_kind_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String gameKindName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.game_type
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Integer gameType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.game_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String gameName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.bet_time
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private Date betTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.agents
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String agents;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.world
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String world;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.corprator
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String corprator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.superior
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String superior;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.company
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.comm_agent
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal commAgent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.comm_world
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal commWorld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.comm_corprator
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal commCorprator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.comm_superior
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal commSuperior;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.comm_branch
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private BigDecimal commBranch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_report.last_comm
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	private String lastComm;
	
	
	private BigDecimal jackpot;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.id
	 * @return  the value of ds_report.id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.id
	 * @param id  the value for ds_report.id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.username
	 * @return  the value of ds_report.username
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.username
	 * @param username  the value for ds_report.username
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.bet_count
	 * @return  the value of ds_report.bet_count
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Integer getBetCount() {
		return betCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.bet_count
	 * @param betCount  the value for ds_report.bet_count
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setBetCount(Integer betCount) {
		this.betCount = betCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.betamount
	 * @return  the value of ds_report.betamount
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getBetamount() {
		return betamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.betamount
	 * @param betamount  the value for ds_report.betamount
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setBetamount(BigDecimal betamount) {
		this.betamount = betamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.winlose
	 * @return  the value of ds_report.winlose
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getWinlose() {
		return winlose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.winlose
	 * @param winlose  the value for ds_report.winlose
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setWinlose(BigDecimal winlose) {
		this.winlose = winlose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.validamount
	 * @return  the value of ds_report.validamount
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getValidamount() {
		return validamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.validamount
	 * @param validamount  the value for ds_report.validamount
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setValidamount(BigDecimal validamount) {
		this.validamount = validamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.site_id
	 * @return  the value of ds_report.site_id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.site_id
	 * @param siteId  the value for ds_report.site_id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.live_id
	 * @return  the value of ds_report.live_id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Byte getLiveId() {
		return liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.live_id
	 * @param liveId  the value for ds_report.live_id
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setLiveId(Byte liveId) {
		this.liveId = liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.live_name
	 * @return  the value of ds_report.live_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getLiveName() {
		return liveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.live_name
	 * @param liveName  the value for ds_report.live_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setLiveName(String liveName) {
		this.liveName = liveName == null ? null : liveName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.game_kind
	 * @return  the value of ds_report.game_kind
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Integer getGameKind() {
		return gameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.game_kind
	 * @param gameKind  the value for ds_report.game_kind
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setGameKind(Integer gameKind) {
		this.gameKind = gameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.game_kind_name
	 * @return  the value of ds_report.game_kind_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getGameKindName() {
		return gameKindName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.game_kind_name
	 * @param gameKindName  the value for ds_report.game_kind_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setGameKindName(String gameKindName) {
		this.gameKindName = gameKindName == null ? null : gameKindName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.game_type
	 * @return  the value of ds_report.game_type
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Integer getGameType() {
		return gameType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.game_type
	 * @param gameType  the value for ds_report.game_type
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setGameType(Integer gameType) {
		this.gameType = gameType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.game_name
	 * @return  the value of ds_report.game_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getGameName() {
		return gameName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.game_name
	 * @param gameName  the value for ds_report.game_name
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setGameName(String gameName) {
		this.gameName = gameName == null ? null : gameName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.bet_time
	 * @return  the value of ds_report.bet_time
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public Date getBetTime() {
		return betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.bet_time
	 * @param betTime  the value for ds_report.bet_time
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setBetTime(Date betTime) {
		this.betTime = betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.agents
	 * @return  the value of ds_report.agents
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getAgents() {
		return agents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.agents
	 * @param agents  the value for ds_report.agents
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setAgents(String agents) {
		this.agents = agents == null ? null : agents.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.world
	 * @return  the value of ds_report.world
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getWorld() {
		return world;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.world
	 * @param world  the value for ds_report.world
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setWorld(String world) {
		this.world = world == null ? null : world.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.corprator
	 * @return  the value of ds_report.corprator
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getCorprator() {
		return corprator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.corprator
	 * @param corprator  the value for ds_report.corprator
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCorprator(String corprator) {
		this.corprator = corprator == null ? null : corprator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.superior
	 * @return  the value of ds_report.superior
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getSuperior() {
		return superior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.superior
	 * @param superior  the value for ds_report.superior
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setSuperior(String superior) {
		this.superior = superior == null ? null : superior.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.company
	 * @return  the value of ds_report.company
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.company
	 * @param company  the value for ds_report.company
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.comm_agent
	 * @return  the value of ds_report.comm_agent
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getCommAgent() {
		return commAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.comm_agent
	 * @param commAgent  the value for ds_report.comm_agent
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCommAgent(BigDecimal commAgent) {
		this.commAgent = commAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.comm_world
	 * @return  the value of ds_report.comm_world
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getCommWorld() {
		return commWorld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.comm_world
	 * @param commWorld  the value for ds_report.comm_world
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCommWorld(BigDecimal commWorld) {
		this.commWorld = commWorld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.comm_corprator
	 * @return  the value of ds_report.comm_corprator
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getCommCorprator() {
		return commCorprator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.comm_corprator
	 * @param commCorprator  the value for ds_report.comm_corprator
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCommCorprator(BigDecimal commCorprator) {
		this.commCorprator = commCorprator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.comm_superior
	 * @return  the value of ds_report.comm_superior
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getCommSuperior() {
		return commSuperior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.comm_superior
	 * @param commSuperior  the value for ds_report.comm_superior
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCommSuperior(BigDecimal commSuperior) {
		this.commSuperior = commSuperior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.comm_branch
	 * @return  the value of ds_report.comm_branch
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public BigDecimal getCommBranch() {
		return commBranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.comm_branch
	 * @param commBranch  the value for ds_report.comm_branch
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setCommBranch(BigDecimal commBranch) {
		this.commBranch = commBranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_report.last_comm
	 * @return  the value of ds_report.last_comm
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public String getLastComm() {
		return lastComm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_report.last_comm
	 * @param lastComm  the value for ds_report.last_comm
	 * @mbggenerated  Mon Oct 05 16:42:44 CST 2015
	 */
	public void setLastComm(String lastComm) {
		this.lastComm = lastComm == null ? null : lastComm.trim();
	}
	
	

	public BigDecimal getJackpot() {
		return jackpot;
	}

	public void setJackpot(BigDecimal jackpot) {
		this.jackpot = jackpot;
	}

	@Override
	public String toString() {
		return "DsReportEntity [id=" + id + ", username=" + username
				+ ", betCount=" + betCount + ", betamount=" + betamount
				+ ", winlose=" + winlose + ", validamount=" + validamount
				+ ", siteId=" + siteId + ", liveId=" + liveId + ", liveName="
				+ liveName + ", gameKind=" + gameKind + ", gameKindName="
				+ gameKindName + ", gameType=" + gameType + ", gameName="
				+ gameName + ", betTime=" + betTime + ", agents=" + agents
				+ ", world=" + world + ", corprator=" + corprator
				+ ", superior=" + superior + ", company=" + company
				+ ", commAgent=" + commAgent + ", commWorld=" + commWorld
				+ ", commCorprator=" + commCorprator + ", commSuperior="
				+ commSuperior + ", commBranch=" + commBranch + ", lastComm="
				+ lastComm + ", jackpot=" + jackpot + "]";
	}
}