package com.kg.live.entity;

import java.util.Date;

public class FenfenLottoGameLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_fenfen_game_log.id
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_fenfen_game_log.qishu
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    private String qishu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_fenfen_game_log.ip
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_fenfen_game_log.create_time
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_fenfen_game_log.id
     *
     * @return the value of ds_fenfen_game_log.id
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_fenfen_game_log.id
     *
     * @param id the value for ds_fenfen_game_log.id
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_fenfen_game_log.qishu
     *
     * @return the value of ds_fenfen_game_log.qishu
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public String getQishu() {
        return qishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_fenfen_game_log.qishu
     *
     * @param qishu the value for ds_fenfen_game_log.qishu
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public void setQishu(String qishu) {
        this.qishu = qishu == null ? null : qishu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_fenfen_game_log.ip
     *
     * @return the value of ds_fenfen_game_log.ip
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_fenfen_game_log.ip
     *
     * @param ip the value for ds_fenfen_game_log.ip
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_fenfen_game_log.create_time
     *
     * @return the value of ds_fenfen_game_log.create_time
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_fenfen_game_log.create_time
     *
     * @param createTime the value for ds_fenfen_game_log.create_time
     *
     * @mbggenerated Tue Oct 13 15:57:55 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}