package com.kg.live.entity;

import java.util.Date;

public class lottoConfEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.id
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.lotto_type
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private String lottoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.lotto_name
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private String lottoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.table_name
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.status
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.create_time
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_lotto_conf.update_time
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.id
     *
     * @return the value of ds_lotto_conf.id
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.id
     *
     * @param id the value for ds_lotto_conf.id
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.lotto_type
     *
     * @return the value of ds_lotto_conf.lotto_type
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public String getLottoType() {
        return lottoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.lotto_type
     *
     * @param lottoType the value for ds_lotto_conf.lotto_type
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setLottoType(String lottoType) {
        this.lottoType = lottoType == null ? null : lottoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.lotto_name
     *
     * @return the value of ds_lotto_conf.lotto_name
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public String getLottoName() {
        return lottoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.lotto_name
     *
     * @param lottoName the value for ds_lotto_conf.lotto_name
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setLottoName(String lottoName) {
        this.lottoName = lottoName == null ? null : lottoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.table_name
     *
     * @return the value of ds_lotto_conf.table_name
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.table_name
     *
     * @param tableName the value for ds_lotto_conf.table_name
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.status
     *
     * @return the value of ds_lotto_conf.status
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.status
     *
     * @param status the value for ds_lotto_conf.status
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.create_time
     *
     * @return the value of ds_lotto_conf.create_time
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.create_time
     *
     * @param createTime the value for ds_lotto_conf.create_time
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_lotto_conf.update_time
     *
     * @return the value of ds_lotto_conf.update_time
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_lotto_conf.update_time
     *
     * @param updateTime the value for ds_lotto_conf.update_time
     *
     * @mbggenerated Tue Jan 30 15:37:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	@Override
	public String toString() {
		return "lottoConfEntity [id=" + id + ", lottoType=" + lottoType
				+ ", lottoName=" + lottoName + ", tableName=" + tableName
				+ ", status=" + status + ", createTime=" + createTime
				+ ", updateTime=" + updateTime + "]";
	}
    
    
}