package com.kg.live.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class M8SportEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public M8SportEntityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFetchIdIsNull() {
			addCriterion("fetch_id is null");
			return (Criteria) this;
		}

		public Criteria andFetchIdIsNotNull() {
			addCriterion("fetch_id is not null");
			return (Criteria) this;
		}

		public Criteria andFetchIdEqualTo(Long value) {
			addCriterion("fetch_id =", value, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdNotEqualTo(Long value) {
			addCriterion("fetch_id <>", value, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdGreaterThan(Long value) {
			addCriterion("fetch_id >", value, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdGreaterThanOrEqualTo(Long value) {
			addCriterion("fetch_id >=", value, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdLessThan(Long value) {
			addCriterion("fetch_id <", value, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdLessThanOrEqualTo(Long value) {
			addCriterion("fetch_id <=", value, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdIn(List<Long> values) {
			addCriterion("fetch_id in", values, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdNotIn(List<Long> values) {
			addCriterion("fetch_id not in", values, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdBetween(Long value1, Long value2) {
			addCriterion("fetch_id between", value1, value2, "fetchId");
			return (Criteria) this;
		}

		public Criteria andFetchIdNotBetween(Long value1, Long value2) {
			addCriterion("fetch_id not between", value1, value2, "fetchId");
			return (Criteria) this;
		}

		public Criteria andBetIdIsNull() {
			addCriterion("bet_id is null");
			return (Criteria) this;
		}

		public Criteria andBetIdIsNotNull() {
			addCriterion("bet_id is not null");
			return (Criteria) this;
		}

		public Criteria andBetIdEqualTo(String value) {
			addCriterion("bet_id =", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdNotEqualTo(String value) {
			addCriterion("bet_id <>", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdGreaterThan(String value) {
			addCriterion("bet_id >", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdGreaterThanOrEqualTo(String value) {
			addCriterion("bet_id >=", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdLessThan(String value) {
			addCriterion("bet_id <", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdLessThanOrEqualTo(String value) {
			addCriterion("bet_id <=", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdLike(String value) {
			addCriterion("bet_id like", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdNotLike(String value) {
			addCriterion("bet_id not like", value, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdIn(List<String> values) {
			addCriterion("bet_id in", values, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdNotIn(List<String> values) {
			addCriterion("bet_id not in", values, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdBetween(String value1, String value2) {
			addCriterion("bet_id between", value1, value2, "betId");
			return (Criteria) this;
		}

		public Criteria andBetIdNotBetween(String value1, String value2) {
			addCriterion("bet_id not between", value1, value2, "betId");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNull() {
			addCriterion("site_id is null");
			return (Criteria) this;
		}

		public Criteria andSiteIdIsNotNull() {
			addCriterion("site_id is not null");
			return (Criteria) this;
		}

		public Criteria andSiteIdEqualTo(Integer value) {
			addCriterion("site_id =", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotEqualTo(Integer value) {
			addCriterion("site_id <>", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThan(Integer value) {
			addCriterion("site_id >", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("site_id >=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThan(Integer value) {
			addCriterion("site_id <", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdLessThanOrEqualTo(Integer value) {
			addCriterion("site_id <=", value, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdIn(List<Integer> values) {
			addCriterion("site_id in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotIn(List<Integer> values) {
			addCriterion("site_id not in", values, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdBetween(Integer value1, Integer value2) {
			addCriterion("site_id between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andSiteIdNotBetween(Integer value1, Integer value2) {
			addCriterion("site_id not between", value1, value2, "siteId");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andBetAmountIsNull() {
			addCriterion("bet_amount is null");
			return (Criteria) this;
		}

		public Criteria andBetAmountIsNotNull() {
			addCriterion("bet_amount is not null");
			return (Criteria) this;
		}

		public Criteria andBetAmountEqualTo(BigDecimal value) {
			addCriterion("bet_amount =", value, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountNotEqualTo(BigDecimal value) {
			addCriterion("bet_amount <>", value, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountGreaterThan(BigDecimal value) {
			addCriterion("bet_amount >", value, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("bet_amount >=", value, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountLessThan(BigDecimal value) {
			addCriterion("bet_amount <", value, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("bet_amount <=", value, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountIn(List<BigDecimal> values) {
			addCriterion("bet_amount in", values, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountNotIn(List<BigDecimal> values) {
			addCriterion("bet_amount not in", values, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("bet_amount between", value1, value2, "betAmount");
			return (Criteria) this;
		}

		public Criteria andBetAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("bet_amount not between", value1, value2, "betAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountIsNull() {
			addCriterion("win_amount is null");
			return (Criteria) this;
		}

		public Criteria andWinAmountIsNotNull() {
			addCriterion("win_amount is not null");
			return (Criteria) this;
		}

		public Criteria andWinAmountEqualTo(BigDecimal value) {
			addCriterion("win_amount =", value, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountNotEqualTo(BigDecimal value) {
			addCriterion("win_amount <>", value, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountGreaterThan(BigDecimal value) {
			addCriterion("win_amount >", value, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("win_amount >=", value, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountLessThan(BigDecimal value) {
			addCriterion("win_amount <", value, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("win_amount <=", value, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountIn(List<BigDecimal> values) {
			addCriterion("win_amount in", values, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountNotIn(List<BigDecimal> values) {
			addCriterion("win_amount not in", values, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("win_amount between", value1, value2, "winAmount");
			return (Criteria) this;
		}

		public Criteria andWinAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("win_amount not between", value1, value2, "winAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountIsNull() {
			addCriterion("commission_amount is null");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountIsNotNull() {
			addCriterion("commission_amount is not null");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountEqualTo(BigDecimal value) {
			addCriterion("commission_amount =", value, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountNotEqualTo(BigDecimal value) {
			addCriterion("commission_amount <>", value, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountGreaterThan(BigDecimal value) {
			addCriterion("commission_amount >", value, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("commission_amount >=", value, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountLessThan(BigDecimal value) {
			addCriterion("commission_amount <", value, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("commission_amount <=", value, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountIn(List<BigDecimal> values) {
			addCriterion("commission_amount in", values, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountNotIn(List<BigDecimal> values) {
			addCriterion("commission_amount not in", values, "commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("commission_amount between", value1, value2,
					"commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("commission_amount not between", value1, value2,
					"commissionAmount");
			return (Criteria) this;
		}

		public Criteria andCommissionIsNull() {
			addCriterion("commission is null");
			return (Criteria) this;
		}

		public Criteria andCommissionIsNotNull() {
			addCriterion("commission is not null");
			return (Criteria) this;
		}

		public Criteria andCommissionEqualTo(BigDecimal value) {
			addCriterion("commission =", value, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionNotEqualTo(BigDecimal value) {
			addCriterion("commission <>", value, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionGreaterThan(BigDecimal value) {
			addCriterion("commission >", value, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("commission >=", value, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionLessThan(BigDecimal value) {
			addCriterion("commission <", value, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionLessThanOrEqualTo(BigDecimal value) {
			addCriterion("commission <=", value, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionIn(List<BigDecimal> values) {
			addCriterion("commission in", values, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionNotIn(List<BigDecimal> values) {
			addCriterion("commission not in", values, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("commission between", value1, value2, "commission");
			return (Criteria) this;
		}

		public Criteria andCommissionNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("commission not between", value1, value2, "commission");
			return (Criteria) this;
		}

		public Criteria andResultIsNull() {
			addCriterion("result is null");
			return (Criteria) this;
		}

		public Criteria andResultIsNotNull() {
			addCriterion("result is not null");
			return (Criteria) this;
		}

		public Criteria andResultEqualTo(String value) {
			addCriterion("result =", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotEqualTo(String value) {
			addCriterion("result <>", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThan(String value) {
			addCriterion("result >", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultGreaterThanOrEqualTo(String value) {
			addCriterion("result >=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThan(String value) {
			addCriterion("result <", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLessThanOrEqualTo(String value) {
			addCriterion("result <=", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultLike(String value) {
			addCriterion("result like", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotLike(String value) {
			addCriterion("result not like", value, "result");
			return (Criteria) this;
		}

		public Criteria andResultIn(List<String> values) {
			addCriterion("result in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotIn(List<String> values) {
			addCriterion("result not in", values, "result");
			return (Criteria) this;
		}

		public Criteria andResultBetween(String value1, String value2) {
			addCriterion("result between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andResultNotBetween(String value1, String value2) {
			addCriterion("result not between", value1, value2, "result");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeIsNull() {
			addCriterion("win_lose_type is null");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeIsNotNull() {
			addCriterion("win_lose_type is not null");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeEqualTo(Integer value) {
			addCriterion("win_lose_type =", value, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeNotEqualTo(Integer value) {
			addCriterion("win_lose_type <>", value, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeGreaterThan(Integer value) {
			addCriterion("win_lose_type >", value, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("win_lose_type >=", value, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeLessThan(Integer value) {
			addCriterion("win_lose_type <", value, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeLessThanOrEqualTo(Integer value) {
			addCriterion("win_lose_type <=", value, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeIn(List<Integer> values) {
			addCriterion("win_lose_type in", values, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeNotIn(List<Integer> values) {
			addCriterion("win_lose_type not in", values, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeBetween(Integer value1, Integer value2) {
			addCriterion("win_lose_type between", value1, value2, "winLoseType");
			return (Criteria) this;
		}

		public Criteria andWinLoseTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("win_lose_type not between", value1, value2,
					"winLoseType");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIsNull() {
			addCriterion("last_modify_time is null");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIsNotNull() {
			addCriterion("last_modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeEqualTo(Date value) {
			addCriterion("last_modify_time =", value, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotEqualTo(Date value) {
			addCriterion("last_modify_time <>", value, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeGreaterThan(Date value) {
			addCriterion("last_modify_time >", value, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("last_modify_time >=", value, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeLessThan(Date value) {
			addCriterion("last_modify_time <", value, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("last_modify_time <=", value, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeIn(List<Date> values) {
			addCriterion("last_modify_time in", values, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotIn(List<Date> values) {
			addCriterion("last_modify_time not in", values, "lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
			addCriterion("last_modify_time between", value1, value2,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("last_modify_time not between", value1, value2,
					"lastModifyTime");
			return (Criteria) this;
		}

		public Criteria andLeagueIsNull() {
			addCriterion("league is null");
			return (Criteria) this;
		}

		public Criteria andLeagueIsNotNull() {
			addCriterion("league is not null");
			return (Criteria) this;
		}

		public Criteria andLeagueEqualTo(String value) {
			addCriterion("league =", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueNotEqualTo(String value) {
			addCriterion("league <>", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueGreaterThan(String value) {
			addCriterion("league >", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueGreaterThanOrEqualTo(String value) {
			addCriterion("league >=", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueLessThan(String value) {
			addCriterion("league <", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueLessThanOrEqualTo(String value) {
			addCriterion("league <=", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueLike(String value) {
			addCriterion("league like", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueNotLike(String value) {
			addCriterion("league not like", value, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueIn(List<String> values) {
			addCriterion("league in", values, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueNotIn(List<String> values) {
			addCriterion("league not in", values, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueBetween(String value1, String value2) {
			addCriterion("league between", value1, value2, "league");
			return (Criteria) this;
		}

		public Criteria andLeagueNotBetween(String value1, String value2) {
			addCriterion("league not between", value1, value2, "league");
			return (Criteria) this;
		}

		public Criteria andHomeIsNull() {
			addCriterion("home is null");
			return (Criteria) this;
		}

		public Criteria andHomeIsNotNull() {
			addCriterion("home is not null");
			return (Criteria) this;
		}

		public Criteria andHomeEqualTo(String value) {
			addCriterion("home =", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeNotEqualTo(String value) {
			addCriterion("home <>", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeGreaterThan(String value) {
			addCriterion("home >", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeGreaterThanOrEqualTo(String value) {
			addCriterion("home >=", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeLessThan(String value) {
			addCriterion("home <", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeLessThanOrEqualTo(String value) {
			addCriterion("home <=", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeLike(String value) {
			addCriterion("home like", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeNotLike(String value) {
			addCriterion("home not like", value, "home");
			return (Criteria) this;
		}

		public Criteria andHomeIn(List<String> values) {
			addCriterion("home in", values, "home");
			return (Criteria) this;
		}

		public Criteria andHomeNotIn(List<String> values) {
			addCriterion("home not in", values, "home");
			return (Criteria) this;
		}

		public Criteria andHomeBetween(String value1, String value2) {
			addCriterion("home between", value1, value2, "home");
			return (Criteria) this;
		}

		public Criteria andHomeNotBetween(String value1, String value2) {
			addCriterion("home not between", value1, value2, "home");
			return (Criteria) this;
		}

		public Criteria andAwayIsNull() {
			addCriterion("away is null");
			return (Criteria) this;
		}

		public Criteria andAwayIsNotNull() {
			addCriterion("away is not null");
			return (Criteria) this;
		}

		public Criteria andAwayEqualTo(String value) {
			addCriterion("away =", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayNotEqualTo(String value) {
			addCriterion("away <>", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayGreaterThan(String value) {
			addCriterion("away >", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayGreaterThanOrEqualTo(String value) {
			addCriterion("away >=", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayLessThan(String value) {
			addCriterion("away <", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayLessThanOrEqualTo(String value) {
			addCriterion("away <=", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayLike(String value) {
			addCriterion("away like", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayNotLike(String value) {
			addCriterion("away not like", value, "away");
			return (Criteria) this;
		}

		public Criteria andAwayIn(List<String> values) {
			addCriterion("away in", values, "away");
			return (Criteria) this;
		}

		public Criteria andAwayNotIn(List<String> values) {
			addCriterion("away not in", values, "away");
			return (Criteria) this;
		}

		public Criteria andAwayBetween(String value1, String value2) {
			addCriterion("away between", value1, value2, "away");
			return (Criteria) this;
		}

		public Criteria andAwayNotBetween(String value1, String value2) {
			addCriterion("away not between", value1, value2, "away");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andGameIsNull() {
			addCriterion("game is null");
			return (Criteria) this;
		}

		public Criteria andGameIsNotNull() {
			addCriterion("game is not null");
			return (Criteria) this;
		}

		public Criteria andGameEqualTo(String value) {
			addCriterion("game =", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameNotEqualTo(String value) {
			addCriterion("game <>", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameGreaterThan(String value) {
			addCriterion("game >", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameGreaterThanOrEqualTo(String value) {
			addCriterion("game >=", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameLessThan(String value) {
			addCriterion("game <", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameLessThanOrEqualTo(String value) {
			addCriterion("game <=", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameLike(String value) {
			addCriterion("game like", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameNotLike(String value) {
			addCriterion("game not like", value, "game");
			return (Criteria) this;
		}

		public Criteria andGameIn(List<String> values) {
			addCriterion("game in", values, "game");
			return (Criteria) this;
		}

		public Criteria andGameNotIn(List<String> values) {
			addCriterion("game not in", values, "game");
			return (Criteria) this;
		}

		public Criteria andGameBetween(String value1, String value2) {
			addCriterion("game between", value1, value2, "game");
			return (Criteria) this;
		}

		public Criteria andGameNotBetween(String value1, String value2) {
			addCriterion("game not between", value1, value2, "game");
			return (Criteria) this;
		}

		public Criteria andOddsIsNull() {
			addCriterion("odds is null");
			return (Criteria) this;
		}

		public Criteria andOddsIsNotNull() {
			addCriterion("odds is not null");
			return (Criteria) this;
		}

		public Criteria andOddsEqualTo(BigDecimal value) {
			addCriterion("odds =", value, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsNotEqualTo(BigDecimal value) {
			addCriterion("odds <>", value, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsGreaterThan(BigDecimal value) {
			addCriterion("odds >", value, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("odds >=", value, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsLessThan(BigDecimal value) {
			addCriterion("odds <", value, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsLessThanOrEqualTo(BigDecimal value) {
			addCriterion("odds <=", value, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsIn(List<BigDecimal> values) {
			addCriterion("odds in", values, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsNotIn(List<BigDecimal> values) {
			addCriterion("odds not in", values, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("odds between", value1, value2, "odds");
			return (Criteria) this;
		}

		public Criteria andOddsNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("odds not between", value1, value2, "odds");
			return (Criteria) this;
		}

		public Criteria andSideIsNull() {
			addCriterion("side is null");
			return (Criteria) this;
		}

		public Criteria andSideIsNotNull() {
			addCriterion("side is not null");
			return (Criteria) this;
		}

		public Criteria andSideEqualTo(String value) {
			addCriterion("side =", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideNotEqualTo(String value) {
			addCriterion("side <>", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideGreaterThan(String value) {
			addCriterion("side >", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideGreaterThanOrEqualTo(String value) {
			addCriterion("side >=", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideLessThan(String value) {
			addCriterion("side <", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideLessThanOrEqualTo(String value) {
			addCriterion("side <=", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideLike(String value) {
			addCriterion("side like", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideNotLike(String value) {
			addCriterion("side not like", value, "side");
			return (Criteria) this;
		}

		public Criteria andSideIn(List<String> values) {
			addCriterion("side in", values, "side");
			return (Criteria) this;
		}

		public Criteria andSideNotIn(List<String> values) {
			addCriterion("side not in", values, "side");
			return (Criteria) this;
		}

		public Criteria andSideBetween(String value1, String value2) {
			addCriterion("side between", value1, value2, "side");
			return (Criteria) this;
		}

		public Criteria andSideNotBetween(String value1, String value2) {
			addCriterion("side not between", value1, value2, "side");
			return (Criteria) this;
		}

		public Criteria andInfoIsNull() {
			addCriterion("info is null");
			return (Criteria) this;
		}

		public Criteria andInfoIsNotNull() {
			addCriterion("info is not null");
			return (Criteria) this;
		}

		public Criteria andInfoEqualTo(String value) {
			addCriterion("info =", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoNotEqualTo(String value) {
			addCriterion("info <>", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoGreaterThan(String value) {
			addCriterion("info >", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoGreaterThanOrEqualTo(String value) {
			addCriterion("info >=", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoLessThan(String value) {
			addCriterion("info <", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoLessThanOrEqualTo(String value) {
			addCriterion("info <=", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoLike(String value) {
			addCriterion("info like", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoNotLike(String value) {
			addCriterion("info not like", value, "info");
			return (Criteria) this;
		}

		public Criteria andInfoIn(List<String> values) {
			addCriterion("info in", values, "info");
			return (Criteria) this;
		}

		public Criteria andInfoNotIn(List<String> values) {
			addCriterion("info not in", values, "info");
			return (Criteria) this;
		}

		public Criteria andInfoBetween(String value1, String value2) {
			addCriterion("info between", value1, value2, "info");
			return (Criteria) this;
		}

		public Criteria andInfoNotBetween(String value1, String value2) {
			addCriterion("info not between", value1, value2, "info");
			return (Criteria) this;
		}

		public Criteria andHalfIsNull() {
			addCriterion("half is null");
			return (Criteria) this;
		}

		public Criteria andHalfIsNotNull() {
			addCriterion("half is not null");
			return (Criteria) this;
		}

		public Criteria andHalfEqualTo(Byte value) {
			addCriterion("half =", value, "half");
			return (Criteria) this;
		}

		public Criteria andHalfNotEqualTo(Byte value) {
			addCriterion("half <>", value, "half");
			return (Criteria) this;
		}

		public Criteria andHalfGreaterThan(Byte value) {
			addCriterion("half >", value, "half");
			return (Criteria) this;
		}

		public Criteria andHalfGreaterThanOrEqualTo(Byte value) {
			addCriterion("half >=", value, "half");
			return (Criteria) this;
		}

		public Criteria andHalfLessThan(Byte value) {
			addCriterion("half <", value, "half");
			return (Criteria) this;
		}

		public Criteria andHalfLessThanOrEqualTo(Byte value) {
			addCriterion("half <=", value, "half");
			return (Criteria) this;
		}

		public Criteria andHalfIn(List<Byte> values) {
			addCriterion("half in", values, "half");
			return (Criteria) this;
		}

		public Criteria andHalfNotIn(List<Byte> values) {
			addCriterion("half not in", values, "half");
			return (Criteria) this;
		}

		public Criteria andHalfBetween(Byte value1, Byte value2) {
			addCriterion("half between", value1, value2, "half");
			return (Criteria) this;
		}

		public Criteria andHalfNotBetween(Byte value1, Byte value2) {
			addCriterion("half not between", value1, value2, "half");
			return (Criteria) this;
		}

		public Criteria andTransactionDateIsNull() {
			addCriterion("transaction_date is null");
			return (Criteria) this;
		}

		public Criteria andTransactionDateIsNotNull() {
			addCriterion("transaction_date is not null");
			return (Criteria) this;
		}

		public Criteria andTransactionDateEqualTo(Date value) {
			addCriterion("transaction_date =", value, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateNotEqualTo(Date value) {
			addCriterion("transaction_date <>", value, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateGreaterThan(Date value) {
			addCriterion("transaction_date >", value, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateGreaterThanOrEqualTo(Date value) {
			addCriterion("transaction_date >=", value, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateLessThan(Date value) {
			addCriterion("transaction_date <", value, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateLessThanOrEqualTo(Date value) {
			addCriterion("transaction_date <=", value, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateIn(List<Date> values) {
			addCriterion("transaction_date in", values, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateNotIn(List<Date> values) {
			addCriterion("transaction_date not in", values, "transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateBetween(Date value1, Date value2) {
			addCriterion("transaction_date between", value1, value2,
					"transactionDate");
			return (Criteria) this;
		}

		public Criteria andTransactionDateNotBetween(Date value1, Date value2) {
			addCriterion("transaction_date not between", value1, value2,
					"transactionDate");
			return (Criteria) this;
		}

		public Criteria andWorkdateIsNull() {
			addCriterion("workdate is null");
			return (Criteria) this;
		}

		public Criteria andWorkdateIsNotNull() {
			addCriterion("workdate is not null");
			return (Criteria) this;
		}

		public Criteria andWorkdateEqualTo(Date value) {
			addCriterion("workdate =", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateNotEqualTo(Date value) {
			addCriterion("workdate <>", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateGreaterThan(Date value) {
			addCriterion("workdate >", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateGreaterThanOrEqualTo(Date value) {
			addCriterion("workdate >=", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateLessThan(Date value) {
			addCriterion("workdate <", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateLessThanOrEqualTo(Date value) {
			addCriterion("workdate <=", value, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateIn(List<Date> values) {
			addCriterion("workdate in", values, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateNotIn(List<Date> values) {
			addCriterion("workdate not in", values, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateBetween(Date value1, Date value2) {
			addCriterion("workdate between", value1, value2, "workdate");
			return (Criteria) this;
		}

		public Criteria andWorkdateNotBetween(Date value1, Date value2) {
			addCriterion("workdate not between", value1, value2, "workdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateIsNull() {
			addCriterion("matchdate is null");
			return (Criteria) this;
		}

		public Criteria andMatchdateIsNotNull() {
			addCriterion("matchdate is not null");
			return (Criteria) this;
		}

		public Criteria andMatchdateEqualTo(String value) {
			addCriterion("matchdate =", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateNotEqualTo(String value) {
			addCriterion("matchdate <>", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateGreaterThan(String value) {
			addCriterion("matchdate >", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateGreaterThanOrEqualTo(String value) {
			addCriterion("matchdate >=", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateLessThan(String value) {
			addCriterion("matchdate <", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateLessThanOrEqualTo(String value) {
			addCriterion("matchdate <=", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateLike(String value) {
			addCriterion("matchdate like", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateNotLike(String value) {
			addCriterion("matchdate not like", value, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateIn(List<String> values) {
			addCriterion("matchdate in", values, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateNotIn(List<String> values) {
			addCriterion("matchdate not in", values, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateBetween(String value1, String value2) {
			addCriterion("matchdate between", value1, value2, "matchdate");
			return (Criteria) this;
		}

		public Criteria andMatchdateNotBetween(String value1, String value2) {
			addCriterion("matchdate not between", value1, value2, "matchdate");
			return (Criteria) this;
		}

		public Criteria andRunscoreIsNull() {
			addCriterion("runscore is null");
			return (Criteria) this;
		}

		public Criteria andRunscoreIsNotNull() {
			addCriterion("runscore is not null");
			return (Criteria) this;
		}

		public Criteria andRunscoreEqualTo(String value) {
			addCriterion("runscore =", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreNotEqualTo(String value) {
			addCriterion("runscore <>", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreGreaterThan(String value) {
			addCriterion("runscore >", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreGreaterThanOrEqualTo(String value) {
			addCriterion("runscore >=", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreLessThan(String value) {
			addCriterion("runscore <", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreLessThanOrEqualTo(String value) {
			addCriterion("runscore <=", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreLike(String value) {
			addCriterion("runscore like", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreNotLike(String value) {
			addCriterion("runscore not like", value, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreIn(List<String> values) {
			addCriterion("runscore in", values, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreNotIn(List<String> values) {
			addCriterion("runscore not in", values, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreBetween(String value1, String value2) {
			addCriterion("runscore between", value1, value2, "runscore");
			return (Criteria) this;
		}

		public Criteria andRunscoreNotBetween(String value1, String value2) {
			addCriterion("runscore not between", value1, value2, "runscore");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(String value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(String value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(String value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(String value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(String value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(String value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLike(String value) {
			addCriterion("score like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotLike(String value) {
			addCriterion("score not like", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<String> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<String> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(String value1, String value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(String value1, String value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andHtscoreIsNull() {
			addCriterion("htscore is null");
			return (Criteria) this;
		}

		public Criteria andHtscoreIsNotNull() {
			addCriterion("htscore is not null");
			return (Criteria) this;
		}

		public Criteria andHtscoreEqualTo(String value) {
			addCriterion("htscore =", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreNotEqualTo(String value) {
			addCriterion("htscore <>", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreGreaterThan(String value) {
			addCriterion("htscore >", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreGreaterThanOrEqualTo(String value) {
			addCriterion("htscore >=", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreLessThan(String value) {
			addCriterion("htscore <", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreLessThanOrEqualTo(String value) {
			addCriterion("htscore <=", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreLike(String value) {
			addCriterion("htscore like", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreNotLike(String value) {
			addCriterion("htscore not like", value, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreIn(List<String> values) {
			addCriterion("htscore in", values, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreNotIn(List<String> values) {
			addCriterion("htscore not in", values, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreBetween(String value1, String value2) {
			addCriterion("htscore between", value1, value2, "htscore");
			return (Criteria) this;
		}

		public Criteria andHtscoreNotBetween(String value1, String value2) {
			addCriterion("htscore not between", value1, value2, "htscore");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalIsNull() {
			addCriterion("first_last_goal is null");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalIsNotNull() {
			addCriterion("first_last_goal is not null");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalEqualTo(String value) {
			addCriterion("first_last_goal =", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalNotEqualTo(String value) {
			addCriterion("first_last_goal <>", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalGreaterThan(String value) {
			addCriterion("first_last_goal >", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalGreaterThanOrEqualTo(String value) {
			addCriterion("first_last_goal >=", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalLessThan(String value) {
			addCriterion("first_last_goal <", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalLessThanOrEqualTo(String value) {
			addCriterion("first_last_goal <=", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalLike(String value) {
			addCriterion("first_last_goal like", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalNotLike(String value) {
			addCriterion("first_last_goal not like", value, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalIn(List<String> values) {
			addCriterion("first_last_goal in", values, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalNotIn(List<String> values) {
			addCriterion("first_last_goal not in", values, "firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalBetween(String value1, String value2) {
			addCriterion("first_last_goal between", value1, value2,
					"firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andFirstLastGoalNotBetween(String value1, String value2) {
			addCriterion("first_last_goal not between", value1, value2,
					"firstLastGoal");
			return (Criteria) this;
		}

		public Criteria andSportstypeIsNull() {
			addCriterion("sportstype is null");
			return (Criteria) this;
		}

		public Criteria andSportstypeIsNotNull() {
			addCriterion("sportstype is not null");
			return (Criteria) this;
		}

		public Criteria andSportstypeEqualTo(Integer value) {
			addCriterion("sportstype =", value, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeNotEqualTo(Integer value) {
			addCriterion("sportstype <>", value, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeGreaterThan(Integer value) {
			addCriterion("sportstype >", value, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sportstype >=", value, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeLessThan(Integer value) {
			addCriterion("sportstype <", value, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeLessThanOrEqualTo(Integer value) {
			addCriterion("sportstype <=", value, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeIn(List<Integer> values) {
			addCriterion("sportstype in", values, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeNotIn(List<Integer> values) {
			addCriterion("sportstype not in", values, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeBetween(Integer value1, Integer value2) {
			addCriterion("sportstype between", value1, value2, "sportstype");
			return (Criteria) this;
		}

		public Criteria andSportstypeNotBetween(Integer value1, Integer value2) {
			addCriterion("sportstype not between", value1, value2, "sportstype");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andLeagueNameIsNull() {
			addCriterion("league_name is null");
			return (Criteria) this;
		}

		public Criteria andLeagueNameIsNotNull() {
			addCriterion("league_name is not null");
			return (Criteria) this;
		}

		public Criteria andLeagueNameEqualTo(String value) {
			addCriterion("league_name =", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameNotEqualTo(String value) {
			addCriterion("league_name <>", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameGreaterThan(String value) {
			addCriterion("league_name >", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameGreaterThanOrEqualTo(String value) {
			addCriterion("league_name >=", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameLessThan(String value) {
			addCriterion("league_name <", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameLessThanOrEqualTo(String value) {
			addCriterion("league_name <=", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameLike(String value) {
			addCriterion("league_name like", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameNotLike(String value) {
			addCriterion("league_name not like", value, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameIn(List<String> values) {
			addCriterion("league_name in", values, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameNotIn(List<String> values) {
			addCriterion("league_name not in", values, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameBetween(String value1, String value2) {
			addCriterion("league_name between", value1, value2, "leagueName");
			return (Criteria) this;
		}

		public Criteria andLeagueNameNotBetween(String value1, String value2) {
			addCriterion("league_name not between", value1, value2,
					"leagueName");
			return (Criteria) this;
		}

		public Criteria andAwayNameIsNull() {
			addCriterion("away_name is null");
			return (Criteria) this;
		}

		public Criteria andAwayNameIsNotNull() {
			addCriterion("away_name is not null");
			return (Criteria) this;
		}

		public Criteria andAwayNameEqualTo(String value) {
			addCriterion("away_name =", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameNotEqualTo(String value) {
			addCriterion("away_name <>", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameGreaterThan(String value) {
			addCriterion("away_name >", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameGreaterThanOrEqualTo(String value) {
			addCriterion("away_name >=", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameLessThan(String value) {
			addCriterion("away_name <", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameLessThanOrEqualTo(String value) {
			addCriterion("away_name <=", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameLike(String value) {
			addCriterion("away_name like", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameNotLike(String value) {
			addCriterion("away_name not like", value, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameIn(List<String> values) {
			addCriterion("away_name in", values, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameNotIn(List<String> values) {
			addCriterion("away_name not in", values, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameBetween(String value1, String value2) {
			addCriterion("away_name between", value1, value2, "awayName");
			return (Criteria) this;
		}

		public Criteria andAwayNameNotBetween(String value1, String value2) {
			addCriterion("away_name not between", value1, value2, "awayName");
			return (Criteria) this;
		}

		public Criteria andHomeNameIsNull() {
			addCriterion("home_name is null");
			return (Criteria) this;
		}

		public Criteria andHomeNameIsNotNull() {
			addCriterion("home_name is not null");
			return (Criteria) this;
		}

		public Criteria andHomeNameEqualTo(String value) {
			addCriterion("home_name =", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameNotEqualTo(String value) {
			addCriterion("home_name <>", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameGreaterThan(String value) {
			addCriterion("home_name >", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameGreaterThanOrEqualTo(String value) {
			addCriterion("home_name >=", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameLessThan(String value) {
			addCriterion("home_name <", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameLessThanOrEqualTo(String value) {
			addCriterion("home_name <=", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameLike(String value) {
			addCriterion("home_name like", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameNotLike(String value) {
			addCriterion("home_name not like", value, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameIn(List<String> values) {
			addCriterion("home_name in", values, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameNotIn(List<String> values) {
			addCriterion("home_name not in", values, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameBetween(String value1, String value2) {
			addCriterion("home_name between", value1, value2, "homeName");
			return (Criteria) this;
		}

		public Criteria andHomeNameNotBetween(String value1, String value2) {
			addCriterion("home_name not between", value1, value2, "homeName");
			return (Criteria) this;
		}

		public Criteria andFlagIsNull() {
			addCriterion("flag is null");
			return (Criteria) this;
		}

		public Criteria andFlagIsNotNull() {
			addCriterion("flag is not null");
			return (Criteria) this;
		}

		public Criteria andFlagEqualTo(Integer value) {
			addCriterion("flag =", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotEqualTo(Integer value) {
			addCriterion("flag <>", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThan(Integer value) {
			addCriterion("flag >", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("flag >=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThan(Integer value) {
			addCriterion("flag <", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThanOrEqualTo(Integer value) {
			addCriterion("flag <=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagIn(List<Integer> values) {
			addCriterion("flag in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotIn(List<Integer> values) {
			addCriterion("flag not in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagBetween(Integer value1, Integer value2) {
			addCriterion("flag between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("flag not between", value1, value2, "flag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ds_m8_sport
	 * @mbggenerated  Sun Sep 06 14:03:32 EDT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ds_m8_sport
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 14 23:45:51 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}