package com.kg.live.entity;

import java.util.Date;

public class MGRecordTimeEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_mg_record_time.agent
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	private String agent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_mg_record_time.last_get_record_time
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	private Date lastGetRecordTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_mg_record_time.last_update_time
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_mg_record_time.memo
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	private String memo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_mg_record_time.agent
	 * @return  the value of ds_mg_record_time.agent
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public String getAgent() {
		return agent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_mg_record_time.agent
	 * @param agent  the value for ds_mg_record_time.agent
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public void setAgent(String agent) {
		this.agent = agent == null ? null : agent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_mg_record_time.last_get_record_time
	 * @return  the value of ds_mg_record_time.last_get_record_time
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public Date getLastGetRecordTime() {
		return lastGetRecordTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_mg_record_time.last_get_record_time
	 * @param lastGetRecordTime  the value for ds_mg_record_time.last_get_record_time
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public void setLastGetRecordTime(Date lastGetRecordTime) {
		this.lastGetRecordTime = lastGetRecordTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_mg_record_time.last_update_time
	 * @return  the value of ds_mg_record_time.last_update_time
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_mg_record_time.last_update_time
	 * @param lastUpdateTime  the value for ds_mg_record_time.last_update_time
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_mg_record_time.memo
	 * @return  the value of ds_mg_record_time.memo
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_mg_record_time.memo
	 * @param memo  the value for ds_mg_record_time.memo
	 * @mbggenerated  Thu Jul 21 09:25:46 CST 2016
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}
}