package com.kg.live.entity;

public class TotalReportConfigWithBLOBs extends TotalReportConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_total_report_config.select_bet_table_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	private String selectBetTableSql;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_total_report_config.validate_report_select_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	private String validateReportSelectSql;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_total_report_config.vaildate_detail_table_select_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	private String vaildateDetailTableSelectSql;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_total_report_config.delete_report_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	private String deleteReportSql;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column c_total_report_config.delete_temp_table_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	private String deleteTempTableSql;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_total_report_config.select_bet_table_sql
	 * @return  the value of c_total_report_config.select_bet_table_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public String getSelectBetTableSql() {
		return selectBetTableSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_total_report_config.select_bet_table_sql
	 * @param selectBetTableSql  the value for c_total_report_config.select_bet_table_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public void setSelectBetTableSql(String selectBetTableSql) {
		this.selectBetTableSql = selectBetTableSql == null ? null
				: selectBetTableSql.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_total_report_config.validate_report_select_sql
	 * @return  the value of c_total_report_config.validate_report_select_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public String getValidateReportSelectSql() {
		return validateReportSelectSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_total_report_config.validate_report_select_sql
	 * @param validateReportSelectSql  the value for c_total_report_config.validate_report_select_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public void setValidateReportSelectSql(String validateReportSelectSql) {
		this.validateReportSelectSql = validateReportSelectSql == null ? null
				: validateReportSelectSql.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_total_report_config.vaildate_detail_table_select_sql
	 * @return  the value of c_total_report_config.vaildate_detail_table_select_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public String getVaildateDetailTableSelectSql() {
		return vaildateDetailTableSelectSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_total_report_config.vaildate_detail_table_select_sql
	 * @param vaildateDetailTableSelectSql  the value for c_total_report_config.vaildate_detail_table_select_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public void setVaildateDetailTableSelectSql(
			String vaildateDetailTableSelectSql) {
		this.vaildateDetailTableSelectSql = vaildateDetailTableSelectSql == null ? null
				: vaildateDetailTableSelectSql.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_total_report_config.delete_report_sql
	 * @return  the value of c_total_report_config.delete_report_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public String getDeleteReportSql() {
		return deleteReportSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_total_report_config.delete_report_sql
	 * @param deleteReportSql  the value for c_total_report_config.delete_report_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public void setDeleteReportSql(String deleteReportSql) {
		this.deleteReportSql = deleteReportSql == null ? null : deleteReportSql
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column c_total_report_config.delete_temp_table_sql
	 * @return  the value of c_total_report_config.delete_temp_table_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public String getDeleteTempTableSql() {
		return deleteTempTableSql;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column c_total_report_config.delete_temp_table_sql
	 * @param deleteTempTableSql  the value for c_total_report_config.delete_temp_table_sql
	 * @mbggenerated  Sun Jan 17 21:14:23 CST 2016
	 */
	public void setDeleteTempTableSql(String deleteTempTableSql) {
		this.deleteTempTableSql = deleteTempTableSql == null ? null
				: deleteTempTableSql.trim();
	}
}