package com.kg.live.entity;

public class XiaoyuCheckId {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_xiaoyu_check_id.id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_xiaoyu_check_id.trans_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	private String transId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_xiaoyu_check_id.status
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ds_xiaoyu_check_id.create_time
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	private String createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_xiaoyu_check_id.id
	 * @return  the value of ds_xiaoyu_check_id.id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_xiaoyu_check_id.id
	 * @param id  the value for ds_xiaoyu_check_id.id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_xiaoyu_check_id.trans_id
	 * @return  the value of ds_xiaoyu_check_id.trans_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public String getTransId() {
		return transId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_xiaoyu_check_id.trans_id
	 * @param transId  the value for ds_xiaoyu_check_id.trans_id
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public void setTransId(String transId) {
		this.transId = transId == null ? null : transId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_xiaoyu_check_id.status
	 * @return  the value of ds_xiaoyu_check_id.status
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_xiaoyu_check_id.status
	 * @param status  the value for ds_xiaoyu_check_id.status
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ds_xiaoyu_check_id.create_time
	 * @return  the value of ds_xiaoyu_check_id.create_time
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ds_xiaoyu_check_id.create_time
	 * @param createTime  the value for ds_xiaoyu_check_id.create_time
	 * @mbggenerated  Sun May 29 22:09:45 ADT 2016
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}
}